<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ForSyDe" nsURI="https://forsyde.github.io/ForSyDe" nsPrefix="ForSyDe">
  <eSubpackages name="Model" nsURI="https://forsyde.github.io/ForSyDe/Model" nsPrefix="ForSyDe.Model">
    <eSubpackages name="Core" nsURI="https://forsyde.github.io/ForSyDe/Model/Core"
        nsPrefix="ForSyDe.Model.Core">
      <eClassifiers xsi:type="ecore:EDataType" name="IdType" instanceTypeName="String"/>
      <eClassifiers xsi:type="ecore:EClass" name="Customizable">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="customAttributes" upperBound="-1"
            eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="customReferences" upperBound="-1"
            eType="#//Model/Core/Customizable" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Identifiable" eSuperTypes="#//Model/Core/Customizable">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="identifier" ordered="false"
            lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"
            iD="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Vertex" eSuperTypes="#//Model/Core/Identifiable">
        <eStructuralFeatures xsi:type="ecore:EReference" name="inPorts" upperBound="-1"
            eType="#//Model/Core/Port" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="outPorts" upperBound="-1"
            eType="#//Model/Core/Port" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Edge" eSuperTypes="#//Model/Core/Identifiable">
        <eStructuralFeatures xsi:type="ecore:EReference" name="fromVertex" lowerBound="1"
            eType="#//Model/Core/Vertex" eKeys="#//Model/Core/Identifiable/identifier"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="toVertex" lowerBound="1"
            eType="#//Model/Core/Vertex" eKeys="#//Model/Core/Identifiable/identifier"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="toPort" eType="#//Model/Core/Port"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="fromPort" eType="#//Model/Core/Port"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Graph" eSuperTypes="#//Model/Core/Vertex">
        <eStructuralFeatures xsi:type="ecore:EReference" name="vertexes" upperBound="-1"
            eType="#//Model/Core/Vertex" containment="true" resolveProxies="false"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="edges" upperBound="-1"
            eType="#//Model/Core/Edge" containment="true" resolveProxies="false"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Table" eSuperTypes="#//Model/Core/Identifiable">
        <eStructuralFeatures xsi:type="ecore:EReference" name="columns" upperBound="-1"
            eType="#//Model/Core/TableColumn" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Port" eSuperTypes="#//Model/Core/Identifiable">
        <eStructuralFeatures xsi:type="ecore:EReference" name="definer" eType="#//Model/Core/Identifiable"
            eKeys="#//Model/Core/Identifiable/identifier"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="TableColumn">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false"
            lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="values" upperBound="-1"
            eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="typeName" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
      </eClassifiers>
    </eSubpackages>
    <eSubpackages name="Application" nsURI="https://forsyde.github.io/ForSyDe/Model/Application"
        nsPrefix="ForSyDe.Model.Application">
      <eClassifiers xsi:type="ecore:EClass" name="DataType" eSuperTypes="#//Model/Core/Identifiable">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="sizeValue" lowerBound="1"
            eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Integer"
            defaultValueLiteral="0"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="sizeUnit" lowerBound="1"
            eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"
            defaultValueLiteral="&quot;B&quot;"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="category" lowerBound="1"
            eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="ConstructedProcess" eSuperTypes="#//Model/Core/Vertex">
        <eStructuralFeatures xsi:type="ecore:EReference" name="constructor" ordered="false"
            lowerBound="1" eType="#//Model/Application/PrimitiveFunction" containment="true"
            eKeys="#//Model/Core/Identifiable/identifier"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="CompoundProcess" eSuperTypes="#//Model/Core/Graph"/>
      <eClassifiers xsi:type="ecore:EClass" name="Signal" eSuperTypes="#//Model/Core/Vertex">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="descriptors" ordered="false"
            upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="PrimitiveFunction" eSuperTypes="#//Model/Core/Identifiable">
        <eStructuralFeatures xsi:type="ecore:EReference" name="implementations" ordered="false"
            upperBound="-1" eType="#//Model/Application/Implementation" eKeys="#//Model/Core/Identifiable/identifier"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="inPorts" upperBound="-1"
            eType="#//Model/Core/Port" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="outPorts" upperBound="-1"
            eType="#//Model/Core/Port" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="NativeFunction" eSuperTypes="#//Model/Core/Identifiable">
        <eStructuralFeatures xsi:type="ecore:EReference" name="inputs" upperBound="-1"
            eType="#//Model/Core/Port" volatile="true" derived="true" containment="true"
            resolveProxies="false"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="outputs" upperBound="-1"
            eType="#//Model/Core/Port" volatile="true" derived="true" containment="true"
            resolveProxies="false"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="implementations" upperBound="-1"
            eType="#//Model/Application/Implementation" eKeys="#//Model/Core/Identifiable/identifier"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Implementation" eSuperTypes="#//Model/Core/Identifiable">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="target" lowerBound="1"
            eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="source" lowerBound="1"
            eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="SDFComb" eSuperTypes="#//Model/Application/PrimitiveFunction">
        <eStructuralFeatures xsi:type="ecore:EReference" name="actor" lowerBound="1"
            eType="#//Model/Application/NativeFunction" eKeys="#//Model/Core/Identifiable/identifier"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="SDFPrefix" eSuperTypes="#//Model/Application/PrimitiveFunction">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1"
            eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="SYComb" eSuperTypes="#//Model/Application/PrimitiveFunction">
        <eStructuralFeatures xsi:type="ecore:EReference" name="function" eType="#//Model/Application/NativeFunction"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="SYPrefix" eSuperTypes="#//Model/Application/PrimitiveFunction">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1"
            eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="DEPrefix" eSuperTypes="#//Model/Application/PrimitiveFunction">
        <eStructuralFeatures xsi:type="ecore:EReference" name="initializer" lowerBound="1"
            eType="#//Model/Application/NativeFunction" eKeys="#//Model/Core/Identifiable/identifier"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="DEValueComb" eSuperTypes="#//Model/Application/PrimitiveFunction">
        <eStructuralFeatures xsi:type="ecore:EReference" name="combinator" eType="#//Model/Application/NativeFunction"
            eKeys="#//Model/Core/Identifiable/identifier"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="DETagComb" eSuperTypes="#//Model/Application/PrimitiveFunction">
        <eStructuralFeatures xsi:type="ecore:EReference" name="combinator" eType="#//Model/Application/NativeFunction"
            eKeys="#//Model/Core/Identifiable/identifier"/>
      </eClassifiers>
    </eSubpackages>
    <eSubpackages name="Platform" nsURI="https://forsyde.github.io/ForSyDe/Model/Platform"
        nsPrefix="ForSyDe.Model.Platform">
      <eClassifiers xsi:type="ecore:EClass" name="Communication" eSuperTypes="#//Model/Core/Vertex"/>
      <eClassifiers xsi:type="ecore:EClass" name="Computation" eSuperTypes="#//Model/Core/Vertex">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="support" upperBound="-1"
            eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Storage" eSuperTypes="#//Model/Core/Vertex"/>
      <eClassifiers xsi:type="ecore:EClass" name="Interface" eSuperTypes="#//Model/Core/Vertex"/>
      <eClassifiers xsi:type="ecore:EClass" name="Structure" eSuperTypes="#//Model/Core/Graph"/>
      <eClassifiers xsi:type="ecore:EClass" name="TimeDivisionMultiplexer" eSuperTypes="#//Model/Platform/Communication">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxSlots" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Integer"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="minSlots" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Integer"/>
      </eClassifiers>
    </eSubpackages>
    <eSubpackages name="Extra" nsURI="https://forsyde.github.io/ForSyDe/Model/Extra"
        nsPrefix="ForSyDe.Model.Extra">
      <eClassifiers xsi:type="ecore:EClass" name="Extra">
        <eStructuralFeatures xsi:type="ecore:EReference" name="information" upperBound="-1"
            eType="#//Model/Core/Table" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="wcet" eType="#//Model/Core/Table"
            containment="true" eKeys="#//Model/Core/Identifiable/identifier"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Goal" eSuperTypes="#//Model/Core/Identifiable">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="nature" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="process" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="target" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
      </eClassifiers>
    </eSubpackages>
    <eSubpackages name="Refinement" nsURI="https://forsyde.github.io/ForSyDe/Model/Refinement"
        nsPrefix="ForSyDe.Model.Refinement">
      <eClassifiers xsi:type="ecore:EClass" name="SporadicTask" eSuperTypes="#//Model/Core/Vertex"/>
      <eClassifiers xsi:type="ecore:EClass" name="TriggeredTask" eSuperTypes="#//Model/Core/Vertex"/>
      <eClassifiers xsi:type="ecore:EClass" name="StaticCyclicSchedule" eSuperTypes="#//Model/Core/Vertex"/>
    </eSubpackages>
    <eSubpackages name="IO" nsURI="https://forsyde.github.io/ForSyDe/IO" nsPrefix="ForSyDe.Model.IO">
      <eClassifiers xsi:type="ecore:EClass" name="ForSyDeIO">
        <eStructuralFeatures xsi:type="ecore:EReference" name="applications" upperBound="-1"
            eType="#//Model/Core/Vertex" containment="true" resolveProxies="false"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="platforms" upperBound="-1"
            eType="#//Model/Core/Vertex" containment="true" resolveProxies="false"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="extras" eType="#//Model/Extra/Extra"
            containment="true" resolveProxies="false"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="revision" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"
            defaultValueLiteral="&quot;0.5.0&quot;"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="staticRefinement" upperBound="-1"
            eType="#//Model/Core/Vertex" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
            eType="#//Model/Core/Identifiable" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="tables" upperBound="-1"
            eType="#//Model/Core/Table" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="maleableRefinement"
            upperBound="-1" eType="#//Model/Core/Vertex" containment="true"/>
      </eClassifiers>
    </eSubpackages>
  </eSubpackages>
</ecore:EPackage>
