[package]
name = "forsyde-io-libforsyde"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
forsyde-io-core = { path = "../rust-core" }

[build-dependencies]
forsyde-io-generator = { path = "../rust-generator"}
serde.workspace = true
serde_json.workspace = true