/**
 *
 * $Id$
 */
package forsyde.io.eclipse.systemgraph.validation;

import forsyde.io.eclipse.systemgraph.Vertex;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link forsyde.io.eclipse.systemgraph.Edge}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface EdgeValidator {
	boolean validate();

	boolean validateSourceport(String value);
	boolean validateTargetport(String value);
	boolean validateTraits(EList<String> value);
	boolean validateSource(Vertex value);
	boolean validateTarget(Vertex value);
}
