/**
 *
 * $Id$
 */
package forsyde.io.eclipse.systemgraph.validation;

import forsyde.io.eclipse.systemgraph.Edge;
import forsyde.io.eclipse.systemgraph.Vertex;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link forsyde.io.eclipse.systemgraph.ForSyDeSystemGraph}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ForSyDeSystemGraphValidator {
	boolean validate();

	boolean validateNodes(EList<Vertex> value);
	boolean validateEdges(EList<Edge> value);
}
