//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.07 at 04:02:54 PM CET 
//


package forsyde.io.java.adapters.sdf3.elems;

import java.math.BigDecimal;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the forsyde.io.java.adapters.sdf3 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Mpperiod_QNAME = new QName("", "mpperiod");
    private final static QName _Throughput_QNAME = new QName("", "throughput");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: forsyde.io.java.adapters.sdf3
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TimeConstraints }
     * 
     */
    public TimeConstraints createTimeConstraints() {
        return new TimeConstraints();
    }

    /**
     * Create an instance of {@link SystemUsage }
     * 
     */
    public SystemUsage createSystemUsage() {
        return new SystemUsage();
    }

    /**
     * Create an instance of {@link Tile }
     * 
     */
    public Tile createTile() {
        return new Tile();
    }

    /**
     * Create an instance of {@link Processor }
     * 
     */
    public Processor createProcessor() {
        return new Processor();
    }

    /**
     * Create an instance of {@link ExecutionTime }
     * 
     */
    public ExecutionTime createExecutionTime() {
        return new ExecutionTime();
    }

    /**
     * Create an instance of {@link Memory }
     * 
     */
    public Memory createMemory() {
        return new Memory();
    }

    /**
     * Create an instance of {@link StateSize }
     * 
     */
    public StateSize createStateSize() {
        return new StateSize();
    }

    /**
     * Create an instance of {@link Actor }
     * 
     */
    public Actor createActor() {
        return new Actor();
    }

    /**
     * Create an instance of {@link Port }
     * 
     */
    public Port createPort() {
        return new Port();
    }

    /**
     * Create an instance of {@link Channel }
     * 
     */
    public Channel createChannel() {
        return new Channel();
    }

    /**
     * Create an instance of {@link Arbitration }
     * 
     */
    public Arbitration createArbitration() {
        return new Arbitration();
    }

    /**
     * Create an instance of {@link Schedule }
     * 
     */
    public Schedule createSchedule() {
        return new Schedule();
    }

    /**
     * Create an instance of {@link State }
     * 
     */
    public State createState() {
        return new State();
    }

    /**
     * Create an instance of {@link NetworkInterface }
     * 
     */
    public NetworkInterface createNetworkInterface() {
        return new NetworkInterface();
    }

    /**
     * Create an instance of {@link Network }
     * 
     */
    public Network createNetwork() {
        return new Network();
    }

    /**
     * Create an instance of {@link Router }
     * 
     */
    public Router createRouter() {
        return new Router();
    }

    /**
     * Create an instance of {@link Link }
     * 
     */
    public Link createLink() {
        return new Link();
    }

    /**
     * Create an instance of {@link Messages }
     * 
     */
    public Messages createMessages() {
        return new Messages();
    }

    /**
     * Create an instance of {@link SchedulingEntity }
     * 
     */
    public SchedulingEntity createSchedulingEntity() {
        return new SchedulingEntity();
    }

    /**
     * Create an instance of {@link Message }
     * 
     */
    public Message createMessage() {
        return new Message();
    }

    /**
     * Create an instance of {@link MaxplusSchedules }
     * 
     */
    public MaxplusSchedules createMaxplusSchedules() {
        return new MaxplusSchedules();
    }

    /**
     * Create an instance of {@link MpscheduleSteadystate }
     * 
     */
    public MpscheduleSteadystate createMpscheduleSteadystate() {
        return new MpscheduleSteadystate();
    }

    /**
     * Create an instance of {@link MpscheduleChannel }
     * 
     */
    public MpscheduleChannel createMpscheduleChannel() {
        return new MpscheduleChannel();
    }

    /**
     * Create an instance of {@link MpscheduleInitial }
     * 
     */
    public MpscheduleInitial createMpscheduleInitial() {
        return new MpscheduleInitial();
    }

    /**
     * Create an instance of {@link Latency }
     * 
     */
    public Latency createLatency() {
        return new Latency();
    }

    /**
     * Create an instance of {@link ActorProperties }
     * 
     */
    public ActorProperties createActorProperties() {
        return new ActorProperties();
    }

    /**
     * Create an instance of {@link Distribution }
     * 
     */
    public Distribution createDistribution() {
        return new Distribution();
    }

    /**
     * Create an instance of {@link Ch }
     * 
     */
    public Ch createCh() {
        return new Ch();
    }

    /**
     * Create an instance of {@link Switch }
     * 
     */
    public Switch createSwitch() {
        return new Switch();
    }

    /**
     * Create an instance of {@link GraphProperties }
     * 
     */
    public GraphProperties createGraphProperties() {
        return new GraphProperties();
    }

    /**
     * Create an instance of {@link StorageThroughputTradeOffs }
     * 
     */
    public StorageThroughputTradeOffs createStorageThroughputTradeOffs() {
        return new StorageThroughputTradeOffs();
    }

    /**
     * Create an instance of {@link DistributionsSet }
     * 
     */
    public DistributionsSet createDistributionsSet() {
        return new DistributionsSet();
    }

    /**
     * Create an instance of {@link Connection }
     * 
     */
    public Connection createConnection() {
        return new Connection();
    }

    /**
     * Create an instance of {@link Settings }
     * 
     */
    public Settings createSettings() {
        return new Settings();
    }

    /**
     * Create an instance of {@link Mapping }
     * 
     */
    public Mapping createMapping() {
        return new Mapping();
    }

    /**
     * Create an instance of {@link Bandwidth }
     * 
     */
    public Bandwidth createBandwidth() {
        return new Bandwidth();
    }

    /**
     * Create an instance of {@link ApplicationGraph }
     * 
     */
    public ApplicationGraph createApplicationGraph() {
        return new ApplicationGraph();
    }

    /**
     * Create an instance of {@link Sdf }
     * 
     */
    public Sdf createSdf() {
        return new Sdf();
    }

    /**
     * Create an instance of {@link SdfProperties }
     * 
     */
    public SdfProperties createSdfProperties() {
        return new SdfProperties();
    }

    /**
     * Create an instance of {@link ChannelProperties }
     * 
     */
    public ChannelProperties createChannelProperties() {
        return new ChannelProperties();
    }

    /**
     * Create an instance of {@link BufferSize }
     * 
     */
    public BufferSize createBufferSize() {
        return new BufferSize();
    }

    /**
     * Create an instance of {@link TokenSize }
     * 
     */
    public TokenSize createTokenSize() {
        return new TokenSize();
    }

    /**
     * Create an instance of {@link Sdf3 }
     * 
     */
    public Sdf3 createSdf3() {
        return new Sdf3();
    }

    /**
     * Create an instance of {@link ArchitectureGraph }
     * 
     */
    public ArchitectureGraph createArchitectureGraph() {
        return new ArchitectureGraph();
    }

    /**
     * Create an instance of {@link MessagesSet }
     * 
     */
    public MessagesSet createMessagesSet() {
        return new MessagesSet();
    }

    /**
     * Create an instance of {@link Token }
     * 
     */
    public Token createToken() {
        return new Token();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "mpperiod")
    public JAXBElement<BigDecimal> createMpperiod(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_Mpperiod_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "throughput")
    public JAXBElement<BigDecimal> createThroughput(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_Throughput_QNAME, BigDecimal.class, null, value);
    }

}
