/*
 * generated by Xtext 2.25.0
 */
package io.github.forsyde.io.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import io.github.forsyde.io.MetaRuntimeModule;
import io.github.forsyde.io.MetaStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class MetaIdeSetup extends MetaStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new MetaRuntimeModule(), new MetaIdeModule()));
	}
	
}
