<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ForSyDe" nsURI="https://forsyde.github.io/emf" nsPrefix="forsyde">
  <eSubpackages name="Model" nsURI="https://forsyde.github.io/emf/model" nsPrefix="model">
    <eClassifiers xsi:type="ecore:EClass" name="System">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="descriptionVersion" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="processes" ordered="false"
          lowerBound="1" upperBound="-1" eType="#//Model/Process"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="signals" upperBound="-1"
          eType="#//Model/Signal"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="functions" lowerBound="1"
          upperBound="-1" eType="#//Model/Function" changeable="false"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Process">
      <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
          eType="#//Model/Process"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="inputs" upperBound="-1"
          eType="#//Model/Signal"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="outputs" upperBound="-1"
          eType="#//Model/Signal"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="constructor" lowerBound="1"
          eType="#//Model/ProcessConstructor"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Signal">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          defaultValueLiteral="Void"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Function">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="inputs" lowerBound="1"
          transient="true">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        </eGenericType>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="outputs" lowerBound="1"
          transient="true">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        </eGenericType>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ProcessConstructor">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
