/*
 * generated by Xtext 2.25.0
 */
package io.github.forsyde.io;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class MetaRuntimeModule extends AbstractMetaRuntimeModule {
}
