<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ForSyDe" nsURI="https://forsyde.github.io/ForSyDe" nsPrefix="ForSyDe">
  <eSubpackages name="Model" nsURI="https://forsyde.github.io/ForSyDe/Model" nsPrefix="ForSyDe.Model">
    <eSubpackages name="Core" nsURI="https://forsyde.github.io/ForSyDe/Model/Core"
        nsPrefix="ForSyDe.Model.Core">
      <eClassifiers xsi:type="ecore:EDataType" name="IdType" instanceTypeName="String"/>
      <eClassifiers xsi:type="ecore:EDataType" name="PortType" instanceTypeName="String"/>
      <eClassifiers xsi:type="ecore:EClass" name="Vertex">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="identifier" eType="#//Model/Core/IdType"
            iD="true"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="ports" upperBound="-1"
            eType="#//Model/Core/PortType"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Edge">
        <eStructuralFeatures xsi:type="ecore:EReference" name="fromVertex" lowerBound="1"
            eType="#//Model/Core/Vertex"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="toVertex" lowerBound="1"
            eType="#//Model/Core/Vertex"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="toPort" eType="#//Model/Core/PortType"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="fromPort" eType="#//Model/Core/PortType"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="identifier" lowerBound="1"
            eType="#//Model/Core/IdType"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Graph" eSuperTypes="#//Model/Core/Vertex">
        <eStructuralFeatures xsi:type="ecore:EReference" name="vertexes" upperBound="-1"
            eType="#//Model/Core/Vertex" containment="true" resolveProxies="false"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="edges" upperBound="-1"
            eType="#//Model/Core/Edge" containment="true" resolveProxies="false"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Table">
        <eStructuralFeatures xsi:type="ecore:EReference" name="valueColumns" upperBound="-1"
            eType="#//Model/Core/TableValueColumn" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="referenceColumns" upperBound="-1"
            eType="#//Model/Core/TableReferenceColumn" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="TableValueColumn">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="values" upperBound="-1"
            eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="typeName" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="TableReferenceColumn">
        <eStructuralFeatures xsi:type="ecore:EReference" name="references" upperBound="-1"
            eType="#//Model/Core/Vertex"/>
      </eClassifiers>
    </eSubpackages>
    <eSubpackages name="Application" nsURI="https://forsyde.github.io/ForSyDe/Model/Application"
        nsPrefix="ForSyDe.Model.Application">
      <eClassifiers xsi:type="ecore:EClass" name="DataType"/>
      <eClassifiers xsi:type="ecore:EClass" name="SingularDataType" eSuperTypes="#//Model/Application/DataType">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="size" lowerBound="1"
            eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Integer"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="ArrayDataType" eSuperTypes="#//Model/Application/DataType">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="size" lowerBound="1"
            eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Integer"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1"
            eType="#//Model/Application/SingularDataType" containment="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="ConstructedProcess" eSuperTypes="#//Model/Core/Vertex"/>
      <eClassifiers xsi:type="ecore:EClass" name="CompoundProcess" eSuperTypes="#//Model/Core/Graph"/>
      <eClassifiers xsi:type="ecore:EClass" name="Signal" eSuperTypes="#//Model/Core/Vertex">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="descriptors" ordered="false"
            upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="NativeFunction" eSuperTypes="#//Model/Core/Vertex"/>
      <eClassifiers xsi:type="ecore:EClass" name="Implementation" eSuperTypes="#//Model/Core/Vertex">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="target" lowerBound="1"
            eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="source" lowerBound="1"
            eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="SDFComb" eSuperTypes="#//Model/Core/Vertex"/>
      <eClassifiers xsi:type="ecore:EClass" name="SDFPrefix" eSuperTypes="#//Model/Core/Vertex">
        <eTypeParameters name="prefixDataType"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="prefix" lowerBound="1">
          <eGenericType eTypeParameter="#//Model/Application/SDFPrefix/prefixDataType"/>
        </eStructuralFeatures>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="SYComb" eSuperTypes="#//Model/Core/Vertex"/>
      <eClassifiers xsi:type="ecore:EClass" name="SYPrefix" eSuperTypes="#//Model/Core/Vertex">
        <eTypeParameters name="prefixDataType"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="prefix" lowerBound="1">
          <eGenericType eTypeParameter="#//Model/Application/SYPrefix/prefixDataType"/>
        </eStructuralFeatures>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="DEPrefix" eSuperTypes="#//Model/Core/Vertex"/>
      <eClassifiers xsi:type="ecore:EClass" name="DEValueComb" eSuperTypes="#//Model/Core/Vertex"/>
      <eClassifiers xsi:type="ecore:EClass" name="DETagComb" eSuperTypes="#//Model/Core/Vertex"/>
      <eClassifiers xsi:type="ecore:EClass" name="Implements" eSuperTypes="#//Model/Core/Edge"/>
      <eClassifiers xsi:type="ecore:EClass" name="Constructs" eSuperTypes="#//Model/Core/Edge"/>
      <eClassifiers xsi:type="ecore:EClass" name="Types" eSuperTypes="#//Model/Core/Edge"/>
      <eClassifiers xsi:type="ecore:EClass" name="Takes" eSuperTypes="#//Model/Core/Edge"/>
      <eClassifiers xsi:type="ecore:EClass" name="Writes" eSuperTypes="#//Model/Core/Edge"/>
      <eClassifiers xsi:type="ecore:EClass" name="Reads" eSuperTypes="#//Model/Core/Edge"/>
    </eSubpackages>
    <eSubpackages name="Platform" nsURI="https://forsyde.github.io/ForSyDe/Model/Platform"
        nsPrefix="ForSyDe.Model.Platform">
      <eClassifiers xsi:type="ecore:EClass" name="Communication" eSuperTypes="#//Model/Core/Vertex"/>
      <eClassifiers xsi:type="ecore:EClass" name="Computation" eSuperTypes="#//Model/Core/Vertex">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="support" upperBound="-1"
            eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Storage" eSuperTypes="#//Model/Core/Vertex"/>
      <eClassifiers xsi:type="ecore:EClass" name="Interface" eSuperTypes="#//Model/Core/Vertex"/>
      <eClassifiers xsi:type="ecore:EClass" name="Structure" eSuperTypes="#//Model/Core/Graph"/>
      <eClassifiers xsi:type="ecore:EClass" name="TimeDivisionMultiplexer" eSuperTypes="#//Model/Platform/Communication">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxSlots" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Integer"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="minSlots" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Integer"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="ComputationalTile" eSuperTypes="#//Model/Platform/Computation"/>
    </eSubpackages>
    <eSubpackages name="Extra" nsURI="https://forsyde.github.io/ForSyDe/Model/Extra"
        nsPrefix="ForSyDe.Model.Extra">
      <eClassifiers xsi:type="ecore:EClass" name="Goal">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="nature" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="process" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="target" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Throughput" eSuperTypes="#//Model/Extra/Goal"/>
    </eSubpackages>
    <eSubpackages name="Refinement" nsURI="https://forsyde.github.io/ForSyDe/Model/Refinement"
        nsPrefix="ForSyDe.Model.Refinement">
      <eClassifiers xsi:type="ecore:EClass" name="SporadicTask" eSuperTypes="#//Model/Core/Vertex">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="minArrival" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Integer"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="TriggeredTask" eSuperTypes="#//Model/Core/Vertex"/>
      <eClassifiers xsi:type="ecore:EClass" name="StaticCyclicSchedule" eSuperTypes="#//Model/Core/Vertex"/>
      <eClassifiers xsi:type="ecore:EClass" name="FixedPriorityScheduler" eSuperTypes="#//Model/Core/Vertex">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="preemptive" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean"
            defaultValueLiteral="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="CustomScheduler" eSuperTypes="#//Model/Core/Vertex"/>
      <eClassifiers xsi:type="ecore:EClass" name="RoundRobinScheduler" eSuperTypes="#//Model/Core/Vertex"/>
    </eSubpackages>
    <eSubpackages name="IO" nsURI="https://forsyde.github.io/ForSyDe/IO" nsPrefix="ForSyDe.Model.IO">
      <eClassifiers xsi:type="ecore:EClass" name="ForSyDeIO">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"
            defaultValueLiteral="&quot;0.1.2&quot;"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="tables" upperBound="-1"
            eType="#//Model/Core/Table" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="vertexes" upperBound="-1"
            eType="#//Model/Core/Vertex" containment="true"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="edges" upperBound="-1"
            eType="#//Model/Core/Edge" containment="true"/>
      </eClassifiers>
    </eSubpackages>
  </eSubpackages>
</ecore:EPackage>
