<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="Types" nsURI="https://forsyde.github.io/Types" nsPrefix="Types">
  <eSubpackages name="Extra" nsURI="https://forsyde.github.io/ForSyDe/Model/Extra"
      nsPrefix="">
    <eClassifiers xsi:type="ecore:EClass" name="Goal"/>
    <eClassifiers xsi:type="ecore:EClass" name="Throughput" eSuperTypes="#//Extra/Goal"/>
  </eSubpackages>
  <eSubpackages name="Refinement" nsURI="https://forsyde.github.io/ForSyDe/Model/Refinement"
      nsPrefix="">
    <eClassifiers xsi:type="ecore:EClass" name="StaticCyclicScheduler"/>
    <eClassifiers xsi:type="ecore:EClass" name="FixedPriorityScheduler">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="preemptive" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean"
          defaultValueLiteral="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CustomScheduler"/>
    <eClassifiers xsi:type="ecore:EClass" name="RoundRobinScheduler"/>
  </eSubpackages>
  <eSubpackages name="Vertexes" nsURI="https://forsyde.github.io/ForSyDe/Model/Vertexes"
      nsPrefix="VertexTypes">
    <eClassifiers xsi:type="ecore:EClass" name="Process"/>
    <eClassifiers xsi:type="ecore:EClass" name="SporadicTask" eSuperTypes="#//Vertexes/TriggeredTask #//Vertexes/AbstractOrdering">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="minArrival" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Integer"
          defaultValueLiteral="0"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TriggeredTask" eSuperTypes="#//Vertexes/AbstractOrdering"/>
    <eClassifiers xsi:type="ecore:EClass" name="AbstractOrdering" eSuperTypes="#//Vertexes/AbstractGrouping"/>
    <eClassifiers xsi:type="ecore:EClass" name="AbstractGrouping"/>
    <eClassifiers xsi:type="ecore:EClass" name="AbstractPhysicalComponent"/>
    <eClassifiers xsi:type="ecore:EClass" name="AbstractProcessingComponent" eSuperTypes="#//Vertexes/AbstractPhysicalComponent"/>
    <eClassifiers xsi:type="ecore:EClass" name="AbstractCommunicationComponent" eSuperTypes="#//Vertexes/AbstractPhysicalComponent"/>
    <eClassifiers xsi:type="ecore:EClass" name="TimeDivisionMultiplexer" eSuperTypes="#//Vertexes/AbstractCommunicationComponent">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="slots" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Integer"
          defaultValueLiteral="1"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="WCET">
      <eStructuralFeatures xsi:type="ecore:EReference" name="process" lowerBound="1"
          eType="#//Vertexes/Process"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="processor" lowerBound="1"
          eType="#//Vertexes/AbstractProcessingComponent"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="time" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Integer"
          defaultValueLiteral="0"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AbstractStorageComponent" eSuperTypes="#//Vertexes/AbstractPhysicalComponent"/>
    <eClassifiers xsi:type="ecore:EClass" name="ComputationalTile"/>
    <eClassifiers xsi:type="ecore:EClass" name="AbsractInterfaceComponent" eSuperTypes="#//Vertexes/AbstractPhysicalComponent"/>
    <eClassifiers xsi:type="ecore:EClass" name="ConstructedProcess" eSuperTypes="#//Vertexes/Process"/>
    <eClassifiers xsi:type="ecore:EClass" name="Signal"/>
    <eClassifiers xsi:type="ecore:EClass" name="FIFOSignal" eSuperTypes="#//Vertexes/Signal"/>
    <eClassifiers xsi:type="ecore:EClass" name="WCCT">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="time" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Integer"
          defaultValueLiteral="0"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="sender" lowerBound="1"
          eType="#//Vertexes/AbstractProcessingComponent"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="reciever" lowerBound="1"
          eType="#//Vertexes/AbstractProcessingComponent"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="interconnect" lowerBound="1"
          eType="#//Vertexes/AbstractCommunicationComponent"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="signal" lowerBound="1"
          eType="#//Vertexes/Signal"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Function"/>
    <eClassifiers xsi:type="ecore:EClass" name="LabelSignal" eSuperTypes="#//Vertexes/Signal"/>
    <eSubpackages name="MoC" nsURI="https://forsyde.github.io/ForSyDe/Model/MoC" nsPrefix="">
      <eSubpackages name="SY" nsURI="https://forsyde.github.io/ForSyDe/Model/MoC/SY"
          nsPrefix="">
        <eClassifiers xsi:type="ecore:EClass" name="SYComb">
          <eStructuralFeatures xsi:type="ecore:EReference" name="combinator" lowerBound="1"
              eType="#//Vertexes/Function"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="constructed" lowerBound="1"
              eType="#//Vertexes/Process"/>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="SYPrefix"/>
      </eSubpackages>
      <eSubpackages name="SDF" nsURI="https://forsyde.github.io/ForSyDe/Model/MoC/SDF"
          nsPrefix="">
        <eClassifiers xsi:type="ecore:EClass" name="SDFComb">
          <eStructuralFeatures xsi:type="ecore:EReference" name="combinator" lowerBound="1"
              eType="#//Vertexes/Function"/>
          <eStructuralFeatures xsi:type="ecore:EReference" name="constructed" lowerBound="1"
              eType="#//Vertexes/Process"/>
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="production" transient="true">
            <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
              <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
              <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Integer"/>
            </eGenericType>
          </eStructuralFeatures>
          <eStructuralFeatures xsi:type="ecore:EAttribute" name="consumption" transient="true">
            <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
              <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
              <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Integer"/>
            </eGenericType>
          </eStructuralFeatures>
        </eClassifiers>
        <eClassifiers xsi:type="ecore:EClass" name="SDFPrefix"/>
      </eSubpackages>
      <eSubpackages name="DE" nsURI="https://forsyde.github.io/ForSyDe/Model/MoC/DE"
          nsPrefix="">
        <eClassifiers xsi:type="ecore:EClass" name="DEPrefix"/>
        <eClassifiers xsi:type="ecore:EClass" name="DEValueComb"/>
        <eClassifiers xsi:type="ecore:EClass" name="DETagComb"/>
      </eSubpackages>
    </eSubpackages>
  </eSubpackages>
  <eSubpackages name="Edges" nsURI="https://forsyde.github.io/ForSyDe/Model/Edges"
      nsPrefix="EdgesTypes">
    <eClassifiers xsi:type="ecore:EClass" name="AbstractPhysicalConnection"/>
    <eClassifiers xsi:type="ecore:EClass" name="Scheduling"/>
    <eClassifiers xsi:type="ecore:EClass" name="Mapping"/>
    <eClassifiers xsi:type="ecore:EClass" name="Writes"/>
    <eClassifiers xsi:type="ecore:EClass" name="Reads"/>
    <eClassifiers xsi:type="ecore:EClass" name="Input"/>
    <eClassifiers xsi:type="ecore:EClass" name="Output"/>
    <eClassifiers xsi:type="ecore:EClass" name="Annotation"/>
    <eClassifiers xsi:type="ecore:EClass" name="Construction"/>
    <eClassifiers xsi:type="ecore:EClass" name="Expansion"/>
  </eSubpackages>
  <eSubpackages name="Ports" nsURI="https://forsyde.github.io/ForSyDe/Model/Ports"
      nsPrefix="PortsTypes">
    <eClassifiers xsi:type="ecore:EClass" name="Host"/>
    <eClassifiers xsi:type="ecore:EClass" name="OrderedExecution"/>
    <eClassifiers xsi:type="ecore:EClass" name="AbstractHardwarePort"/>
  </eSubpackages>
</ecore:EPackage>
