/*
 * generated by Xtext 2.25.0
 */
package io.github.forsyde.io.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractMetaScopeProvider extends DelegatingScopeProvider {
}
