/**
 * generated by Xtext 2.25.0
 */
package io.github.forsyde.io.meta;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Edge Trait</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link io.github.forsyde.io.meta.EdgeTrait#getName <em>Name</em>}</li>
 *   <li>{@link io.github.forsyde.io.meta.EdgeTrait#getRefines <em>Refines</em>}</li>
 *   <li>{@link io.github.forsyde.io.meta.EdgeTrait#getSpecs <em>Specs</em>}</li>
 * </ul>
 *
 * @see io.github.forsyde.io.meta.MetaPackage#getEdgeTrait()
 * @model
 * @generated
 */
public interface EdgeTrait extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see io.github.forsyde.io.meta.MetaPackage#getEdgeTrait_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link io.github.forsyde.io.meta.EdgeTrait#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Refines</b></em>' reference list.
   * The list contents are of type {@link io.github.forsyde.io.meta.EdgeTrait}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Refines</em>' reference list.
   * @see io.github.forsyde.io.meta.MetaPackage#getEdgeTrait_Refines()
   * @model
   * @generated
   */
  EList<EdgeTrait> getRefines();

  /**
   * Returns the value of the '<em><b>Specs</b></em>' containment reference list.
   * The list contents are of type {@link io.github.forsyde.io.meta.EdgeTraitConstraint}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Specs</em>' containment reference list.
   * @see io.github.forsyde.io.meta.MetaPackage#getEdgeTrait_Specs()
   * @model containment="true"
   * @generated
   */
  EList<EdgeTraitConstraint> getSpecs();

} // EdgeTrait
