/**
 * generated by Xtext 2.25.0
 */
package io.github.forsyde.io.meta;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * &lt;!-- begin-user-doc --&gt;
 * A representation of the model object '<em><b>Edge Trait</b>&lt;/em&gt;'.
 * &lt;!-- end-user-doc --&gt;
 *
 * &lt; &gt;
 * The following features are supported:
 * &lt;/p&gt;
 * &lt; &gt;
 *   <li>{@link io.github.forsyde.io.meta.EdgeTrait#getName <em>Name</em>}&lt;/li&gt;
 *   <li>{@link io.github.forsyde.io.meta.EdgeTrait#getRefines <em>Refines</em>}&lt;/li&gt;
 *   <li>{@link io.github.forsyde.io.meta.EdgeTrait#getSpecs <em>Specs</em>}&lt;/li&gt;
 * &lt;/ul&gt;
 *
 * @see io.github.forsyde.io.meta.MetaPackage#getEdgeTrait()
 * @model
 * @generated
 */
public interface EdgeTrait extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b>&lt;/em&gt;' attribute.
   * &lt;!-- begin-user-doc --&gt;
   * &lt;!-- end-user-doc --&gt;
   * @return the value of the '<em>Name&lt;/em&gt;' attribute.
   * @see #setName(String)
   * @see io.github.forsyde.io.meta.MetaPackage#getEdgeTrait_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link io.github.forsyde.io.meta.EdgeTrait#getName <em>Name&lt;/em&gt;}' attribute.
   * &lt;!-- begin-user-doc --&gt;
   * &lt;!-- end-user-doc --&gt;
   * @param value the new value of the '<em>Name&lt;/em&gt;' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Refines</b>&lt;/em&gt;' reference list.
   * The list contents are of type {@link io.github.forsyde.io.meta.EdgeTrait}.
   * &lt;!-- begin-user-doc --&gt;
   * &lt;!-- end-user-doc --&gt;
   * @return the value of the '<em>Refines&lt;/em&gt;' reference list.
   * @see io.github.forsyde.io.meta.MetaPackage#getEdgeTrait_Refines()
   * @model
   * @generated
   */
  EList<EdgeTrait> getRefines();

  /**
   * Returns the value of the '<em><b>Specs</b>&lt;/em&gt;' containment reference list.
   * The list contents are of type {@link io.github.forsyde.io.meta.EdgeTraitConstraint}.
   * &lt;!-- begin-user-doc --&gt;
   * &lt;!-- end-user-doc --&gt;
   * @return the value of the '<em>Specs&lt;/em&gt;' containment reference list.
   * @see io.github.forsyde.io.meta.MetaPackage#getEdgeTrait_Specs()
   * @model containment="true"
   * @generated
   */
  EList<EdgeTraitConstraint> getSpecs();

} // EdgeTrait
