/**
 * generated by Xtext 2.25.0
 */
package io.github.forsyde.io.meta;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Edge Trait Constraint</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link io.github.forsyde.io.meta.EdgeTraitConstraint#isTarget <em>Target</em>}</li>
 *   <li>{@link io.github.forsyde.io.meta.EdgeTraitConstraint#isSource <em>Source</em>}</li>
 *   <li>{@link io.github.forsyde.io.meta.EdgeTraitConstraint#getFilter <em>Filter</em>}</li>
 * </ul>
 *
 * @see io.github.forsyde.io.meta.MetaPackage#getEdgeTraitConstraint()
 * @model
 * @generated
 */
public interface EdgeTraitConstraint extends EObject
{
  /**
   * Returns the value of the '<em><b>Target</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Target</em>' attribute.
   * @see #setTarget(boolean)
   * @see io.github.forsyde.io.meta.MetaPackage#getEdgeTraitConstraint_Target()
   * @model
   * @generated
   */
  boolean isTarget();

  /**
   * Sets the value of the '{@link io.github.forsyde.io.meta.EdgeTraitConstraint#isTarget <em>Target</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Target</em>' attribute.
   * @see #isTarget()
   * @generated
   */
  void setTarget(boolean value);

  /**
   * Returns the value of the '<em><b>Source</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Source</em>' attribute.
   * @see #setSource(boolean)
   * @see io.github.forsyde.io.meta.MetaPackage#getEdgeTraitConstraint_Source()
   * @model
   * @generated
   */
  boolean isSource();

  /**
   * Sets the value of the '{@link io.github.forsyde.io.meta.EdgeTraitConstraint#isSource <em>Source</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Source</em>' attribute.
   * @see #isSource()
   * @generated
   */
  void setSource(boolean value);

  /**
   * Returns the value of the '<em><b>Filter</b></em>' reference list.
   * The list contents are of type {@link io.github.forsyde.io.meta.VertexTrait}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Filter</em>' reference list.
   * @see io.github.forsyde.io.meta.MetaPackage#getEdgeTraitConstraint_Filter()
   * @model
   * @generated
   */
  EList<VertexTrait> getFilter();

} // EdgeTraitConstraint
