/**
 * generated by Xtext 2.25.0
 */
package io.github.forsyde.io.meta;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see io.github.forsyde.io.meta.MetaPackage
 * @generated
 */
public interface MetaFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MetaFactory eINSTANCE = io.github.forsyde.io.meta.impl.MetaFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Model</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Model</em>'.
   * @generated
   */
  Model createModel();

  /**
   * Returns a new object of class '<em>Vertex Trait</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Vertex Trait</em>'.
   * @generated
   */
  VertexTrait createVertexTrait();

  /**
   * Returns a new object of class '<em>Vertex Trait Property</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Vertex Trait Property</em>'.
   * @generated
   */
  VertexTraitProperty createVertexTraitProperty();

  /**
   * Returns a new object of class '<em>Vertex Trait Property Type</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Vertex Trait Property Type</em>'.
   * @generated
   */
  VertexTraitPropertyType createVertexTraitPropertyType();

  /**
   * Returns a new object of class '<em>Vertex Trait Int Property</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Vertex Trait Int Property</em>'.
   * @generated
   */
  VertexTraitIntProperty createVertexTraitIntProperty();

  /**
   * Returns a new object of class '<em>Vertex Trait Real Property</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Vertex Trait Real Property</em>'.
   * @generated
   */
  VertexTraitRealProperty createVertexTraitRealProperty();

  /**
   * Returns a new object of class '<em>Vertex Trait Bool Property</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Vertex Trait Bool Property</em>'.
   * @generated
   */
  VertexTraitBoolProperty createVertexTraitBoolProperty();

  /**
   * Returns a new object of class '<em>Vertex Trait String Property</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Vertex Trait String Property</em>'.
   * @generated
   */
  VertexTraitStringProperty createVertexTraitStringProperty();

  /**
   * Returns a new object of class '<em>Vertex Trait Array Property</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Vertex Trait Array Property</em>'.
   * @generated
   */
  VertexTraitArrayProperty createVertexTraitArrayProperty();

  /**
   * Returns a new object of class '<em>Vertex Trait Object Property</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Vertex Trait Object Property</em>'.
   * @generated
   */
  VertexTraitObjectProperty createVertexTraitObjectProperty();

  /**
   * Returns a new object of class '<em>Vertex Trait Port</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Vertex Trait Port</em>'.
   * @generated
   */
  VertexTraitPort createVertexTraitPort();

  /**
   * Returns a new object of class '<em>Edge Trait</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Edge Trait</em>'.
   * @generated
   */
  EdgeTrait createEdgeTrait();

  /**
   * Returns a new object of class '<em>Edge Trait Constraint</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Edge Trait Constraint</em>'.
   * @generated
   */
  EdgeTraitConstraint createEdgeTraitConstraint();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  MetaPackage getMetaPackage();

} //MetaFactory
