/**
 * generated by Xtext 2.25.0
 */
package io.github.forsyde.io.meta;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see io.github.forsyde.io.meta.MetaFactory
 * @model kind="package"
 * @generated
 */
public interface MetaPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "meta";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.github.io/forsyde/io/Meta";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "meta";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MetaPackage eINSTANCE = io.github.forsyde.io.meta.impl.MetaPackageImpl.init();

  /**
   * The meta object id for the '{@link io.github.forsyde.io.meta.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see io.github.forsyde.io.meta.impl.ModelImpl
   * @see io.github.forsyde.io.meta.impl.MetaPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Traits</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__TRAITS = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link io.github.forsyde.io.meta.impl.VertexTraitImpl <em>Vertex Trait</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see io.github.forsyde.io.meta.impl.VertexTraitImpl
   * @see io.github.forsyde.io.meta.impl.MetaPackageImpl#getVertexTrait()
   * @generated
   */
  int VERTEX_TRAIT = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VERTEX_TRAIT__NAME = 0;

  /**
   * The feature id for the '<em><b>Refines</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VERTEX_TRAIT__REFINES = 1;

  /**
   * The feature id for the '<em><b>Ports</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VERTEX_TRAIT__PORTS = 2;

  /**
   * The feature id for the '<em><b>Properties</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VERTEX_TRAIT__PROPERTIES = 3;

  /**
   * The number of structural features of the '<em>Vertex Trait</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VERTEX_TRAIT_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link io.github.forsyde.io.meta.impl.VertexTraitPropertyImpl <em>Vertex Trait Property</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see io.github.forsyde.io.meta.impl.VertexTraitPropertyImpl
   * @see io.github.forsyde.io.meta.impl.MetaPackageImpl#getVertexTraitProperty()
   * @generated
   */
  int VERTEX_TRAIT_PROPERTY = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VERTEX_TRAIT_PROPERTY__NAME = 0;

  /**
   * The feature id for the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VERTEX_TRAIT_PROPERTY__TYPE = 1;

  /**
   * The number of structural features of the '<em>Vertex Trait Property</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VERTEX_TRAIT_PROPERTY_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link io.github.forsyde.io.meta.impl.VertexTraitPropertyTypeImpl <em>Vertex Trait Property Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see io.github.forsyde.io.meta.impl.VertexTraitPropertyTypeImpl
   * @see io.github.forsyde.io.meta.impl.MetaPackageImpl#getVertexTraitPropertyType()
   * @generated
   */
  int VERTEX_TRAIT_PROPERTY_TYPE = 3;

  /**
   * The number of structural features of the '<em>Vertex Trait Property Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VERTEX_TRAIT_PROPERTY_TYPE_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link io.github.forsyde.io.meta.impl.VertexTraitIntPropertyImpl <em>Vertex Trait Int Property</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see io.github.forsyde.io.meta.impl.VertexTraitIntPropertyImpl
   * @see io.github.forsyde.io.meta.impl.MetaPackageImpl#getVertexTraitIntProperty()
   * @generated
   */
  int VERTEX_TRAIT_INT_PROPERTY = 4;

  /**
   * The feature id for the '<em><b>Default</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VERTEX_TRAIT_INT_PROPERTY__DEFAULT = VERTEX_TRAIT_PROPERTY_TYPE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Vertex Trait Int Property</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VERTEX_TRAIT_INT_PROPERTY_FEATURE_COUNT = VERTEX_TRAIT_PROPERTY_TYPE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link io.github.forsyde.io.meta.impl.VertexTraitRealPropertyImpl <em>Vertex Trait Real Property</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see io.github.forsyde.io.meta.impl.VertexTraitRealPropertyImpl
   * @see io.github.forsyde.io.meta.impl.MetaPackageImpl#getVertexTraitRealProperty()
   * @generated
   */
  int VERTEX_TRAIT_REAL_PROPERTY = 5;

  /**
   * The feature id for the '<em><b>Double</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VERTEX_TRAIT_REAL_PROPERTY__DOUBLE = VERTEX_TRAIT_PROPERTY_TYPE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Default</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VERTEX_TRAIT_REAL_PROPERTY__DEFAULT = VERTEX_TRAIT_PROPERTY_TYPE_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Vertex Trait Real Property</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VERTEX_TRAIT_REAL_PROPERTY_FEATURE_COUNT = VERTEX_TRAIT_PROPERTY_TYPE_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link io.github.forsyde.io.meta.impl.VertexTraitBoolPropertyImpl <em>Vertex Trait Bool Property</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see io.github.forsyde.io.meta.impl.VertexTraitBoolPropertyImpl
   * @see io.github.forsyde.io.meta.impl.MetaPackageImpl#getVertexTraitBoolProperty()
   * @generated
   */
  int VERTEX_TRAIT_BOOL_PROPERTY = 6;

  /**
   * The feature id for the '<em><b>Default</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VERTEX_TRAIT_BOOL_PROPERTY__DEFAULT = VERTEX_TRAIT_PROPERTY_TYPE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Vertex Trait Bool Property</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VERTEX_TRAIT_BOOL_PROPERTY_FEATURE_COUNT = VERTEX_TRAIT_PROPERTY_TYPE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link io.github.forsyde.io.meta.impl.VertexTraitStringPropertyImpl <em>Vertex Trait String Property</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see io.github.forsyde.io.meta.impl.VertexTraitStringPropertyImpl
   * @see io.github.forsyde.io.meta.impl.MetaPackageImpl#getVertexTraitStringProperty()
   * @generated
   */
  int VERTEX_TRAIT_STRING_PROPERTY = 7;

  /**
   * The feature id for the '<em><b>Default</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VERTEX_TRAIT_STRING_PROPERTY__DEFAULT = VERTEX_TRAIT_PROPERTY_TYPE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Vertex Trait String Property</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VERTEX_TRAIT_STRING_PROPERTY_FEATURE_COUNT = VERTEX_TRAIT_PROPERTY_TYPE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link io.github.forsyde.io.meta.impl.VertexTraitArrayPropertyImpl <em>Vertex Trait Array Property</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see io.github.forsyde.io.meta.impl.VertexTraitArrayPropertyImpl
   * @see io.github.forsyde.io.meta.impl.MetaPackageImpl#getVertexTraitArrayProperty()
   * @generated
   */
  int VERTEX_TRAIT_ARRAY_PROPERTY = 8;

  /**
   * The feature id for the '<em><b>Item Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VERTEX_TRAIT_ARRAY_PROPERTY__ITEM_TYPE = VERTEX_TRAIT_PROPERTY_TYPE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Vertex Trait Array Property</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VERTEX_TRAIT_ARRAY_PROPERTY_FEATURE_COUNT = VERTEX_TRAIT_PROPERTY_TYPE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link io.github.forsyde.io.meta.impl.VertexTraitObjectPropertyImpl <em>Vertex Trait Object Property</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see io.github.forsyde.io.meta.impl.VertexTraitObjectPropertyImpl
   * @see io.github.forsyde.io.meta.impl.MetaPackageImpl#getVertexTraitObjectProperty()
   * @generated
   */
  int VERTEX_TRAIT_OBJECT_PROPERTY = 9;

  /**
   * The feature id for the '<em><b>Key Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VERTEX_TRAIT_OBJECT_PROPERTY__KEY_TYPE = VERTEX_TRAIT_PROPERTY_TYPE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Value Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VERTEX_TRAIT_OBJECT_PROPERTY__VALUE_TYPE = VERTEX_TRAIT_PROPERTY_TYPE_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Vertex Trait Object Property</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VERTEX_TRAIT_OBJECT_PROPERTY_FEATURE_COUNT = VERTEX_TRAIT_PROPERTY_TYPE_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link io.github.forsyde.io.meta.impl.VertexTraitPortImpl <em>Vertex Trait Port</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see io.github.forsyde.io.meta.impl.VertexTraitPortImpl
   * @see io.github.forsyde.io.meta.impl.MetaPackageImpl#getVertexTraitPort()
   * @generated
   */
  int VERTEX_TRAIT_PORT = 10;

  /**
   * The feature id for the '<em><b>Multiple</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VERTEX_TRAIT_PORT__MULTIPLE = 0;

  /**
   * The feature id for the '<em><b>Ordered</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VERTEX_TRAIT_PORT__ORDERED = 1;

  /**
   * The feature id for the '<em><b>Direction</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VERTEX_TRAIT_PORT__DIRECTION = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VERTEX_TRAIT_PORT__NAME = 3;

  /**
   * The feature id for the '<em><b>Trait</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VERTEX_TRAIT_PORT__TRAIT = 4;

  /**
   * The number of structural features of the '<em>Vertex Trait Port</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VERTEX_TRAIT_PORT_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link io.github.forsyde.io.meta.impl.EdgeTraitImpl <em>Edge Trait</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see io.github.forsyde.io.meta.impl.EdgeTraitImpl
   * @see io.github.forsyde.io.meta.impl.MetaPackageImpl#getEdgeTrait()
   * @generated
   */
  int EDGE_TRAIT = 11;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EDGE_TRAIT__NAME = 0;

  /**
   * The feature id for the '<em><b>Refines</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EDGE_TRAIT__REFINES = 1;

  /**
   * The feature id for the '<em><b>Specs</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EDGE_TRAIT__SPECS = 2;

  /**
   * The number of structural features of the '<em>Edge Trait</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EDGE_TRAIT_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link io.github.forsyde.io.meta.impl.EdgeTraitConstraintImpl <em>Edge Trait Constraint</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see io.github.forsyde.io.meta.impl.EdgeTraitConstraintImpl
   * @see io.github.forsyde.io.meta.impl.MetaPackageImpl#getEdgeTraitConstraint()
   * @generated
   */
  int EDGE_TRAIT_CONSTRAINT = 12;

  /**
   * The feature id for the '<em><b>Target</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EDGE_TRAIT_CONSTRAINT__TARGET = 0;

  /**
   * The feature id for the '<em><b>Source</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EDGE_TRAIT_CONSTRAINT__SOURCE = 1;

  /**
   * The feature id for the '<em><b>Filter</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EDGE_TRAIT_CONSTRAINT__FILTER = 2;

  /**
   * The number of structural features of the '<em>Edge Trait Constraint</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EDGE_TRAIT_CONSTRAINT_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link io.github.forsyde.io.meta.VertexTraitPortDirection <em>Vertex Trait Port Direction</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see io.github.forsyde.io.meta.VertexTraitPortDirection
   * @see io.github.forsyde.io.meta.impl.MetaPackageImpl#getVertexTraitPortDirection()
   * @generated
   */
  int VERTEX_TRAIT_PORT_DIRECTION = 13;


  /**
   * Returns the meta object for class '{@link io.github.forsyde.io.meta.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see io.github.forsyde.io.meta.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link io.github.forsyde.io.meta.Model#getTraits <em>Traits</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Traits</em>'.
   * @see io.github.forsyde.io.meta.Model#getTraits()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Traits();

  /**
   * Returns the meta object for class '{@link io.github.forsyde.io.meta.VertexTrait <em>Vertex Trait</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Vertex Trait</em>'.
   * @see io.github.forsyde.io.meta.VertexTrait
   * @generated
   */
  EClass getVertexTrait();

  /**
   * Returns the meta object for the attribute '{@link io.github.forsyde.io.meta.VertexTrait#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see io.github.forsyde.io.meta.VertexTrait#getName()
   * @see #getVertexTrait()
   * @generated
   */
  EAttribute getVertexTrait_Name();

  /**
   * Returns the meta object for the reference list '{@link io.github.forsyde.io.meta.VertexTrait#getRefines <em>Refines</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Refines</em>'.
   * @see io.github.forsyde.io.meta.VertexTrait#getRefines()
   * @see #getVertexTrait()
   * @generated
   */
  EReference getVertexTrait_Refines();

  /**
   * Returns the meta object for the containment reference list '{@link io.github.forsyde.io.meta.VertexTrait#getPorts <em>Ports</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Ports</em>'.
   * @see io.github.forsyde.io.meta.VertexTrait#getPorts()
   * @see #getVertexTrait()
   * @generated
   */
  EReference getVertexTrait_Ports();

  /**
   * Returns the meta object for the containment reference list '{@link io.github.forsyde.io.meta.VertexTrait#getProperties <em>Properties</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Properties</em>'.
   * @see io.github.forsyde.io.meta.VertexTrait#getProperties()
   * @see #getVertexTrait()
   * @generated
   */
  EReference getVertexTrait_Properties();

  /**
   * Returns the meta object for class '{@link io.github.forsyde.io.meta.VertexTraitProperty <em>Vertex Trait Property</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Vertex Trait Property</em>'.
   * @see io.github.forsyde.io.meta.VertexTraitProperty
   * @generated
   */
  EClass getVertexTraitProperty();

  /**
   * Returns the meta object for the attribute '{@link io.github.forsyde.io.meta.VertexTraitProperty#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see io.github.forsyde.io.meta.VertexTraitProperty#getName()
   * @see #getVertexTraitProperty()
   * @generated
   */
  EAttribute getVertexTraitProperty_Name();

  /**
   * Returns the meta object for the containment reference '{@link io.github.forsyde.io.meta.VertexTraitProperty#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Type</em>'.
   * @see io.github.forsyde.io.meta.VertexTraitProperty#getType()
   * @see #getVertexTraitProperty()
   * @generated
   */
  EReference getVertexTraitProperty_Type();

  /**
   * Returns the meta object for class '{@link io.github.forsyde.io.meta.VertexTraitPropertyType <em>Vertex Trait Property Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Vertex Trait Property Type</em>'.
   * @see io.github.forsyde.io.meta.VertexTraitPropertyType
   * @generated
   */
  EClass getVertexTraitPropertyType();

  /**
   * Returns the meta object for class '{@link io.github.forsyde.io.meta.VertexTraitIntProperty <em>Vertex Trait Int Property</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Vertex Trait Int Property</em>'.
   * @see io.github.forsyde.io.meta.VertexTraitIntProperty
   * @generated
   */
  EClass getVertexTraitIntProperty();

  /**
   * Returns the meta object for the attribute '{@link io.github.forsyde.io.meta.VertexTraitIntProperty#getDefault <em>Default</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Default</em>'.
   * @see io.github.forsyde.io.meta.VertexTraitIntProperty#getDefault()
   * @see #getVertexTraitIntProperty()
   * @generated
   */
  EAttribute getVertexTraitIntProperty_Default();

  /**
   * Returns the meta object for class '{@link io.github.forsyde.io.meta.VertexTraitRealProperty <em>Vertex Trait Real Property</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Vertex Trait Real Property</em>'.
   * @see io.github.forsyde.io.meta.VertexTraitRealProperty
   * @generated
   */
  EClass getVertexTraitRealProperty();

  /**
   * Returns the meta object for the attribute '{@link io.github.forsyde.io.meta.VertexTraitRealProperty#isDouble <em>Double</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Double</em>'.
   * @see io.github.forsyde.io.meta.VertexTraitRealProperty#isDouble()
   * @see #getVertexTraitRealProperty()
   * @generated
   */
  EAttribute getVertexTraitRealProperty_Double();

  /**
   * Returns the meta object for the attribute '{@link io.github.forsyde.io.meta.VertexTraitRealProperty#getDefault <em>Default</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Default</em>'.
   * @see io.github.forsyde.io.meta.VertexTraitRealProperty#getDefault()
   * @see #getVertexTraitRealProperty()
   * @generated
   */
  EAttribute getVertexTraitRealProperty_Default();

  /**
   * Returns the meta object for class '{@link io.github.forsyde.io.meta.VertexTraitBoolProperty <em>Vertex Trait Bool Property</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Vertex Trait Bool Property</em>'.
   * @see io.github.forsyde.io.meta.VertexTraitBoolProperty
   * @generated
   */
  EClass getVertexTraitBoolProperty();

  /**
   * Returns the meta object for the attribute '{@link io.github.forsyde.io.meta.VertexTraitBoolProperty#isDefault <em>Default</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Default</em>'.
   * @see io.github.forsyde.io.meta.VertexTraitBoolProperty#isDefault()
   * @see #getVertexTraitBoolProperty()
   * @generated
   */
  EAttribute getVertexTraitBoolProperty_Default();

  /**
   * Returns the meta object for class '{@link io.github.forsyde.io.meta.VertexTraitStringProperty <em>Vertex Trait String Property</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Vertex Trait String Property</em>'.
   * @see io.github.forsyde.io.meta.VertexTraitStringProperty
   * @generated
   */
  EClass getVertexTraitStringProperty();

  /**
   * Returns the meta object for the attribute '{@link io.github.forsyde.io.meta.VertexTraitStringProperty#getDefault <em>Default</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Default</em>'.
   * @see io.github.forsyde.io.meta.VertexTraitStringProperty#getDefault()
   * @see #getVertexTraitStringProperty()
   * @generated
   */
  EAttribute getVertexTraitStringProperty_Default();

  /**
   * Returns the meta object for class '{@link io.github.forsyde.io.meta.VertexTraitArrayProperty <em>Vertex Trait Array Property</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Vertex Trait Array Property</em>'.
   * @see io.github.forsyde.io.meta.VertexTraitArrayProperty
   * @generated
   */
  EClass getVertexTraitArrayProperty();

  /**
   * Returns the meta object for the containment reference '{@link io.github.forsyde.io.meta.VertexTraitArrayProperty#getItemType <em>Item Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Item Type</em>'.
   * @see io.github.forsyde.io.meta.VertexTraitArrayProperty#getItemType()
   * @see #getVertexTraitArrayProperty()
   * @generated
   */
  EReference getVertexTraitArrayProperty_ItemType();

  /**
   * Returns the meta object for class '{@link io.github.forsyde.io.meta.VertexTraitObjectProperty <em>Vertex Trait Object Property</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Vertex Trait Object Property</em>'.
   * @see io.github.forsyde.io.meta.VertexTraitObjectProperty
   * @generated
   */
  EClass getVertexTraitObjectProperty();

  /**
   * Returns the meta object for the containment reference '{@link io.github.forsyde.io.meta.VertexTraitObjectProperty#getKeyType <em>Key Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Key Type</em>'.
   * @see io.github.forsyde.io.meta.VertexTraitObjectProperty#getKeyType()
   * @see #getVertexTraitObjectProperty()
   * @generated
   */
  EReference getVertexTraitObjectProperty_KeyType();

  /**
   * Returns the meta object for the containment reference '{@link io.github.forsyde.io.meta.VertexTraitObjectProperty#getValueType <em>Value Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Value Type</em>'.
   * @see io.github.forsyde.io.meta.VertexTraitObjectProperty#getValueType()
   * @see #getVertexTraitObjectProperty()
   * @generated
   */
  EReference getVertexTraitObjectProperty_ValueType();

  /**
   * Returns the meta object for class '{@link io.github.forsyde.io.meta.VertexTraitPort <em>Vertex Trait Port</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Vertex Trait Port</em>'.
   * @see io.github.forsyde.io.meta.VertexTraitPort
   * @generated
   */
  EClass getVertexTraitPort();

  /**
   * Returns the meta object for the attribute '{@link io.github.forsyde.io.meta.VertexTraitPort#isMultiple <em>Multiple</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Multiple</em>'.
   * @see io.github.forsyde.io.meta.VertexTraitPort#isMultiple()
   * @see #getVertexTraitPort()
   * @generated
   */
  EAttribute getVertexTraitPort_Multiple();

  /**
   * Returns the meta object for the attribute '{@link io.github.forsyde.io.meta.VertexTraitPort#isOrdered <em>Ordered</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Ordered</em>'.
   * @see io.github.forsyde.io.meta.VertexTraitPort#isOrdered()
   * @see #getVertexTraitPort()
   * @generated
   */
  EAttribute getVertexTraitPort_Ordered();

  /**
   * Returns the meta object for the attribute '{@link io.github.forsyde.io.meta.VertexTraitPort#getDirection <em>Direction</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Direction</em>'.
   * @see io.github.forsyde.io.meta.VertexTraitPort#getDirection()
   * @see #getVertexTraitPort()
   * @generated
   */
  EAttribute getVertexTraitPort_Direction();

  /**
   * Returns the meta object for the attribute '{@link io.github.forsyde.io.meta.VertexTraitPort#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see io.github.forsyde.io.meta.VertexTraitPort#getName()
   * @see #getVertexTraitPort()
   * @generated
   */
  EAttribute getVertexTraitPort_Name();

  /**
   * Returns the meta object for the reference '{@link io.github.forsyde.io.meta.VertexTraitPort#getTrait <em>Trait</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Trait</em>'.
   * @see io.github.forsyde.io.meta.VertexTraitPort#getTrait()
   * @see #getVertexTraitPort()
   * @generated
   */
  EReference getVertexTraitPort_Trait();

  /**
   * Returns the meta object for class '{@link io.github.forsyde.io.meta.EdgeTrait <em>Edge Trait</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Edge Trait</em>'.
   * @see io.github.forsyde.io.meta.EdgeTrait
   * @generated
   */
  EClass getEdgeTrait();

  /**
   * Returns the meta object for the attribute '{@link io.github.forsyde.io.meta.EdgeTrait#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see io.github.forsyde.io.meta.EdgeTrait#getName()
   * @see #getEdgeTrait()
   * @generated
   */
  EAttribute getEdgeTrait_Name();

  /**
   * Returns the meta object for the reference list '{@link io.github.forsyde.io.meta.EdgeTrait#getRefines <em>Refines</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Refines</em>'.
   * @see io.github.forsyde.io.meta.EdgeTrait#getRefines()
   * @see #getEdgeTrait()
   * @generated
   */
  EReference getEdgeTrait_Refines();

  /**
   * Returns the meta object for the containment reference list '{@link io.github.forsyde.io.meta.EdgeTrait#getSpecs <em>Specs</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Specs</em>'.
   * @see io.github.forsyde.io.meta.EdgeTrait#getSpecs()
   * @see #getEdgeTrait()
   * @generated
   */
  EReference getEdgeTrait_Specs();

  /**
   * Returns the meta object for class '{@link io.github.forsyde.io.meta.EdgeTraitConstraint <em>Edge Trait Constraint</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Edge Trait Constraint</em>'.
   * @see io.github.forsyde.io.meta.EdgeTraitConstraint
   * @generated
   */
  EClass getEdgeTraitConstraint();

  /**
   * Returns the meta object for the attribute '{@link io.github.forsyde.io.meta.EdgeTraitConstraint#isTarget <em>Target</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Target</em>'.
   * @see io.github.forsyde.io.meta.EdgeTraitConstraint#isTarget()
   * @see #getEdgeTraitConstraint()
   * @generated
   */
  EAttribute getEdgeTraitConstraint_Target();

  /**
   * Returns the meta object for the attribute '{@link io.github.forsyde.io.meta.EdgeTraitConstraint#isSource <em>Source</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Source</em>'.
   * @see io.github.forsyde.io.meta.EdgeTraitConstraint#isSource()
   * @see #getEdgeTraitConstraint()
   * @generated
   */
  EAttribute getEdgeTraitConstraint_Source();

  /**
   * Returns the meta object for the reference list '{@link io.github.forsyde.io.meta.EdgeTraitConstraint#getFilter <em>Filter</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Filter</em>'.
   * @see io.github.forsyde.io.meta.EdgeTraitConstraint#getFilter()
   * @see #getEdgeTraitConstraint()
   * @generated
   */
  EReference getEdgeTraitConstraint_Filter();

  /**
   * Returns the meta object for enum '{@link io.github.forsyde.io.meta.VertexTraitPortDirection <em>Vertex Trait Port Direction</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Vertex Trait Port Direction</em>'.
   * @see io.github.forsyde.io.meta.VertexTraitPortDirection
   * @generated
   */
  EEnum getVertexTraitPortDirection();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  MetaFactory getMetaFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link io.github.forsyde.io.meta.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see io.github.forsyde.io.meta.impl.ModelImpl
     * @see io.github.forsyde.io.meta.impl.MetaPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Traits</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__TRAITS = eINSTANCE.getModel_Traits();

    /**
     * The meta object literal for the '{@link io.github.forsyde.io.meta.impl.VertexTraitImpl <em>Vertex Trait</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see io.github.forsyde.io.meta.impl.VertexTraitImpl
     * @see io.github.forsyde.io.meta.impl.MetaPackageImpl#getVertexTrait()
     * @generated
     */
    EClass VERTEX_TRAIT = eINSTANCE.getVertexTrait();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VERTEX_TRAIT__NAME = eINSTANCE.getVertexTrait_Name();

    /**
     * The meta object literal for the '<em><b>Refines</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VERTEX_TRAIT__REFINES = eINSTANCE.getVertexTrait_Refines();

    /**
     * The meta object literal for the '<em><b>Ports</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VERTEX_TRAIT__PORTS = eINSTANCE.getVertexTrait_Ports();

    /**
     * The meta object literal for the '<em><b>Properties</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VERTEX_TRAIT__PROPERTIES = eINSTANCE.getVertexTrait_Properties();

    /**
     * The meta object literal for the '{@link io.github.forsyde.io.meta.impl.VertexTraitPropertyImpl <em>Vertex Trait Property</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see io.github.forsyde.io.meta.impl.VertexTraitPropertyImpl
     * @see io.github.forsyde.io.meta.impl.MetaPackageImpl#getVertexTraitProperty()
     * @generated
     */
    EClass VERTEX_TRAIT_PROPERTY = eINSTANCE.getVertexTraitProperty();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VERTEX_TRAIT_PROPERTY__NAME = eINSTANCE.getVertexTraitProperty_Name();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VERTEX_TRAIT_PROPERTY__TYPE = eINSTANCE.getVertexTraitProperty_Type();

    /**
     * The meta object literal for the '{@link io.github.forsyde.io.meta.impl.VertexTraitPropertyTypeImpl <em>Vertex Trait Property Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see io.github.forsyde.io.meta.impl.VertexTraitPropertyTypeImpl
     * @see io.github.forsyde.io.meta.impl.MetaPackageImpl#getVertexTraitPropertyType()
     * @generated
     */
    EClass VERTEX_TRAIT_PROPERTY_TYPE = eINSTANCE.getVertexTraitPropertyType();

    /**
     * The meta object literal for the '{@link io.github.forsyde.io.meta.impl.VertexTraitIntPropertyImpl <em>Vertex Trait Int Property</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see io.github.forsyde.io.meta.impl.VertexTraitIntPropertyImpl
     * @see io.github.forsyde.io.meta.impl.MetaPackageImpl#getVertexTraitIntProperty()
     * @generated
     */
    EClass VERTEX_TRAIT_INT_PROPERTY = eINSTANCE.getVertexTraitIntProperty();

    /**
     * The meta object literal for the '<em><b>Default</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VERTEX_TRAIT_INT_PROPERTY__DEFAULT = eINSTANCE.getVertexTraitIntProperty_Default();

    /**
     * The meta object literal for the '{@link io.github.forsyde.io.meta.impl.VertexTraitRealPropertyImpl <em>Vertex Trait Real Property</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see io.github.forsyde.io.meta.impl.VertexTraitRealPropertyImpl
     * @see io.github.forsyde.io.meta.impl.MetaPackageImpl#getVertexTraitRealProperty()
     * @generated
     */
    EClass VERTEX_TRAIT_REAL_PROPERTY = eINSTANCE.getVertexTraitRealProperty();

    /**
     * The meta object literal for the '<em><b>Double</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VERTEX_TRAIT_REAL_PROPERTY__DOUBLE = eINSTANCE.getVertexTraitRealProperty_Double();

    /**
     * The meta object literal for the '<em><b>Default</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VERTEX_TRAIT_REAL_PROPERTY__DEFAULT = eINSTANCE.getVertexTraitRealProperty_Default();

    /**
     * The meta object literal for the '{@link io.github.forsyde.io.meta.impl.VertexTraitBoolPropertyImpl <em>Vertex Trait Bool Property</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see io.github.forsyde.io.meta.impl.VertexTraitBoolPropertyImpl
     * @see io.github.forsyde.io.meta.impl.MetaPackageImpl#getVertexTraitBoolProperty()
     * @generated
     */
    EClass VERTEX_TRAIT_BOOL_PROPERTY = eINSTANCE.getVertexTraitBoolProperty();

    /**
     * The meta object literal for the '<em><b>Default</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VERTEX_TRAIT_BOOL_PROPERTY__DEFAULT = eINSTANCE.getVertexTraitBoolProperty_Default();

    /**
     * The meta object literal for the '{@link io.github.forsyde.io.meta.impl.VertexTraitStringPropertyImpl <em>Vertex Trait String Property</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see io.github.forsyde.io.meta.impl.VertexTraitStringPropertyImpl
     * @see io.github.forsyde.io.meta.impl.MetaPackageImpl#getVertexTraitStringProperty()
     * @generated
     */
    EClass VERTEX_TRAIT_STRING_PROPERTY = eINSTANCE.getVertexTraitStringProperty();

    /**
     * The meta object literal for the '<em><b>Default</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VERTEX_TRAIT_STRING_PROPERTY__DEFAULT = eINSTANCE.getVertexTraitStringProperty_Default();

    /**
     * The meta object literal for the '{@link io.github.forsyde.io.meta.impl.VertexTraitArrayPropertyImpl <em>Vertex Trait Array Property</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see io.github.forsyde.io.meta.impl.VertexTraitArrayPropertyImpl
     * @see io.github.forsyde.io.meta.impl.MetaPackageImpl#getVertexTraitArrayProperty()
     * @generated
     */
    EClass VERTEX_TRAIT_ARRAY_PROPERTY = eINSTANCE.getVertexTraitArrayProperty();

    /**
     * The meta object literal for the '<em><b>Item Type</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VERTEX_TRAIT_ARRAY_PROPERTY__ITEM_TYPE = eINSTANCE.getVertexTraitArrayProperty_ItemType();

    /**
     * The meta object literal for the '{@link io.github.forsyde.io.meta.impl.VertexTraitObjectPropertyImpl <em>Vertex Trait Object Property</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see io.github.forsyde.io.meta.impl.VertexTraitObjectPropertyImpl
     * @see io.github.forsyde.io.meta.impl.MetaPackageImpl#getVertexTraitObjectProperty()
     * @generated
     */
    EClass VERTEX_TRAIT_OBJECT_PROPERTY = eINSTANCE.getVertexTraitObjectProperty();

    /**
     * The meta object literal for the '<em><b>Key Type</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VERTEX_TRAIT_OBJECT_PROPERTY__KEY_TYPE = eINSTANCE.getVertexTraitObjectProperty_KeyType();

    /**
     * The meta object literal for the '<em><b>Value Type</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VERTEX_TRAIT_OBJECT_PROPERTY__VALUE_TYPE = eINSTANCE.getVertexTraitObjectProperty_ValueType();

    /**
     * The meta object literal for the '{@link io.github.forsyde.io.meta.impl.VertexTraitPortImpl <em>Vertex Trait Port</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see io.github.forsyde.io.meta.impl.VertexTraitPortImpl
     * @see io.github.forsyde.io.meta.impl.MetaPackageImpl#getVertexTraitPort()
     * @generated
     */
    EClass VERTEX_TRAIT_PORT = eINSTANCE.getVertexTraitPort();

    /**
     * The meta object literal for the '<em><b>Multiple</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VERTEX_TRAIT_PORT__MULTIPLE = eINSTANCE.getVertexTraitPort_Multiple();

    /**
     * The meta object literal for the '<em><b>Ordered</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VERTEX_TRAIT_PORT__ORDERED = eINSTANCE.getVertexTraitPort_Ordered();

    /**
     * The meta object literal for the '<em><b>Direction</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VERTEX_TRAIT_PORT__DIRECTION = eINSTANCE.getVertexTraitPort_Direction();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VERTEX_TRAIT_PORT__NAME = eINSTANCE.getVertexTraitPort_Name();

    /**
     * The meta object literal for the '<em><b>Trait</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VERTEX_TRAIT_PORT__TRAIT = eINSTANCE.getVertexTraitPort_Trait();

    /**
     * The meta object literal for the '{@link io.github.forsyde.io.meta.impl.EdgeTraitImpl <em>Edge Trait</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see io.github.forsyde.io.meta.impl.EdgeTraitImpl
     * @see io.github.forsyde.io.meta.impl.MetaPackageImpl#getEdgeTrait()
     * @generated
     */
    EClass EDGE_TRAIT = eINSTANCE.getEdgeTrait();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EDGE_TRAIT__NAME = eINSTANCE.getEdgeTrait_Name();

    /**
     * The meta object literal for the '<em><b>Refines</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EDGE_TRAIT__REFINES = eINSTANCE.getEdgeTrait_Refines();

    /**
     * The meta object literal for the '<em><b>Specs</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EDGE_TRAIT__SPECS = eINSTANCE.getEdgeTrait_Specs();

    /**
     * The meta object literal for the '{@link io.github.forsyde.io.meta.impl.EdgeTraitConstraintImpl <em>Edge Trait Constraint</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see io.github.forsyde.io.meta.impl.EdgeTraitConstraintImpl
     * @see io.github.forsyde.io.meta.impl.MetaPackageImpl#getEdgeTraitConstraint()
     * @generated
     */
    EClass EDGE_TRAIT_CONSTRAINT = eINSTANCE.getEdgeTraitConstraint();

    /**
     * The meta object literal for the '<em><b>Target</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EDGE_TRAIT_CONSTRAINT__TARGET = eINSTANCE.getEdgeTraitConstraint_Target();

    /**
     * The meta object literal for the '<em><b>Source</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EDGE_TRAIT_CONSTRAINT__SOURCE = eINSTANCE.getEdgeTraitConstraint_Source();

    /**
     * The meta object literal for the '<em><b>Filter</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EDGE_TRAIT_CONSTRAINT__FILTER = eINSTANCE.getEdgeTraitConstraint_Filter();

    /**
     * The meta object literal for the '{@link io.github.forsyde.io.meta.VertexTraitPortDirection <em>Vertex Trait Port Direction</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see io.github.forsyde.io.meta.VertexTraitPortDirection
     * @see io.github.forsyde.io.meta.impl.MetaPackageImpl#getVertexTraitPortDirection()
     * @generated
     */
    EEnum VERTEX_TRAIT_PORT_DIRECTION = eINSTANCE.getVertexTraitPortDirection();

  }

} //MetaPackage
