/**
 * generated by Xtext 2.25.0
 */
package io.github.forsyde.io.meta;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * &lt;!-- begin-user-doc --&gt;
 * A representation of the model object '<em><b>Model</b>&lt;/em&gt;'.
 * &lt;!-- end-user-doc --&gt;
 *
 * &lt; &gt;
 * The following features are supported:
 * &lt;/p&gt;
 * &lt; &gt;
 *   <li>{@link io.github.forsyde.io.meta.Model#getTraits <em>Traits</em>}&lt;/li&gt;
 * &lt;/ul&gt;
 *
 * @see io.github.forsyde.io.meta.MetaPackage#getModel()
 * @model
 * @generated
 */
public interface Model extends EObject
{
  /**
   * Returns the value of the '<em><b>Traits</b>&lt;/em&gt;' containment reference list.
   * The list contents are of type {@link org.eclipse.emf.ecore.EObject}.
   * &lt;!-- begin-user-doc --&gt;
   * &lt;!-- end-user-doc --&gt;
   * @return the value of the '<em>Traits&lt;/em&gt;' containment reference list.
   * @see io.github.forsyde.io.meta.MetaPackage#getModel_Traits()
   * @model containment="true"
   * @generated
   */
  EList<EObject> getTraits();

} // Model
