/**
 * generated by Xtext 2.25.0
 */
package io.github.forsyde.io.meta;

import org.eclipse.emf.ecore.EObject;

/**
 * &lt;!-- begin-user-doc --&gt;
 * A representation of the model object '<em><b>Vertex Trait Property</b>&lt;/em&gt;'.
 * &lt;!-- end-user-doc --&gt;
 *
 * &lt; &gt;
 * The following features are supported:
 * &lt;/p&gt;
 * &lt; &gt;
 *   <li>{@link io.github.forsyde.io.meta.VertexTraitProperty#getName <em>Name</em>}&lt;/li&gt;
 *   <li>{@link io.github.forsyde.io.meta.VertexTraitProperty#getType <em>Type</em>}&lt;/li&gt;
 * &lt;/ul&gt;
 *
 * @see io.github.forsyde.io.meta.MetaPackage#getVertexTraitProperty()
 * @model
 * @generated
 */
public interface VertexTraitProperty extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b>&lt;/em&gt;' attribute.
   * &lt;!-- begin-user-doc --&gt;
   * &lt;!-- end-user-doc --&gt;
   * @return the value of the '<em>Name&lt;/em&gt;' attribute.
   * @see #setName(String)
   * @see io.github.forsyde.io.meta.MetaPackage#getVertexTraitProperty_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link io.github.forsyde.io.meta.VertexTraitProperty#getName <em>Name&lt;/em&gt;}' attribute.
   * &lt;!-- begin-user-doc --&gt;
   * &lt;!-- end-user-doc --&gt;
   * @param value the new value of the '<em>Name&lt;/em&gt;' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Type</b>&lt;/em&gt;' containment reference.
   * &lt;!-- begin-user-doc --&gt;
   * &lt;!-- end-user-doc --&gt;
   * @return the value of the '<em>Type&lt;/em&gt;' containment reference.
   * @see #setType(VertexTraitPropertyType)
   * @see io.github.forsyde.io.meta.MetaPackage#getVertexTraitProperty_Type()
   * @model containment="true"
   * @generated
   */
  VertexTraitPropertyType getType();

  /**
   * Sets the value of the '{@link io.github.forsyde.io.meta.VertexTraitProperty#getType <em>Type&lt;/em&gt;}' containment reference.
   * &lt;!-- begin-user-doc --&gt;
   * &lt;!-- end-user-doc --&gt;
   * @param value the new value of the '<em>Type&lt;/em&gt;' containment reference.
   * @see #getType()
   * @generated
   */
  void setType(VertexTraitPropertyType value);

} // VertexTraitProperty
