/**
 * generated by Xtext 2.25.0
 */
package io.github.forsyde.io.meta;


/**
 * &lt;!-- begin-user-doc --&gt;
 * A representation of the model object '<em><b>Vertex Trait Object Property</b>&lt;/em&gt;'.
 * &lt;!-- end-user-doc --&gt;
 *
 * &lt; &gt;
 * The following features are supported:
 * &lt;/p&gt;
 * &lt; &gt;
 *   <li>{@link io.github.forsyde.io.meta.VertexTraitObjectProperty#getKeyType <em>Key Type</em>}&lt;/li&gt;
 *   <li>{@link io.github.forsyde.io.meta.VertexTraitObjectProperty#getValueType <em>Value Type</em>}&lt;/li&gt;
 * &lt;/ul&gt;
 *
 * @see io.github.forsyde.io.meta.MetaPackage#getVertexTraitObjectProperty()
 * @model
 * @generated
 */
public interface VertexTraitObjectProperty extends VertexTraitPropertyType
{
  /**
   * Returns the value of the '<em><b>Key Type</b>&lt;/em&gt;' containment reference.
   * &lt;!-- begin-user-doc --&gt;
   * &lt;!-- end-user-doc --&gt;
   * @return the value of the '<em>Key Type&lt;/em&gt;' containment reference.
   * @see #setKeyType(VertexTraitPropertyType)
   * @see io.github.forsyde.io.meta.MetaPackage#getVertexTraitObjectProperty_KeyType()
   * @model containment="true"
   * @generated
   */
  VertexTraitPropertyType getKeyType();

  /**
   * Sets the value of the '{@link io.github.forsyde.io.meta.VertexTraitObjectProperty#getKeyType <em>Key Type&lt;/em&gt;}' containment reference.
   * &lt;!-- begin-user-doc --&gt;
   * &lt;!-- end-user-doc --&gt;
   * @param value the new value of the '<em>Key Type&lt;/em&gt;' containment reference.
   * @see #getKeyType()
   * @generated
   */
  void setKeyType(VertexTraitPropertyType value);

  /**
   * Returns the value of the '<em><b>Value Type</b>&lt;/em&gt;' containment reference.
   * &lt;!-- begin-user-doc --&gt;
   * &lt;!-- end-user-doc --&gt;
   * @return the value of the '<em>Value Type&lt;/em&gt;' containment reference.
   * @see #setValueType(VertexTraitPropertyType)
   * @see io.github.forsyde.io.meta.MetaPackage#getVertexTraitObjectProperty_ValueType()
   * @model containment="true"
   * @generated
   */
  VertexTraitPropertyType getValueType();

  /**
   * Sets the value of the '{@link io.github.forsyde.io.meta.VertexTraitObjectProperty#getValueType <em>Value Type&lt;/em&gt;}' containment reference.
   * &lt;!-- begin-user-doc --&gt;
   * &lt;!-- end-user-doc --&gt;
   * @param value the new value of the '<em>Value Type&lt;/em&gt;' containment reference.
   * @see #getValueType()
   * @generated
   */
  void setValueType(VertexTraitPropertyType value);

} // VertexTraitObjectProperty
