/**
 * generated by Xtext 2.25.0
 */
package io.github.forsyde.io.meta;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Vertex Trait Real Property</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link io.github.forsyde.io.meta.VertexTraitRealProperty#isDouble <em>Double</em>}</li>
 *   <li>{@link io.github.forsyde.io.meta.VertexTraitRealProperty#getDefault <em>Default</em>}</li>
 * </ul>
 *
 * @see io.github.forsyde.io.meta.MetaPackage#getVertexTraitRealProperty()
 * @model
 * @generated
 */
public interface VertexTraitRealProperty extends VertexTraitPropertyType
{
  /**
   * Returns the value of the '<em><b>Double</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Double</em>' attribute.
   * @see #setDouble(boolean)
   * @see io.github.forsyde.io.meta.MetaPackage#getVertexTraitRealProperty_Double()
   * @model
   * @generated
   */
  boolean isDouble();

  /**
   * Sets the value of the '{@link io.github.forsyde.io.meta.VertexTraitRealProperty#isDouble <em>Double</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Double</em>' attribute.
   * @see #isDouble()
   * @generated
   */
  void setDouble(boolean value);

  /**
   * Returns the value of the '<em><b>Default</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Default</em>' attribute.
   * @see #setDefault(String)
   * @see io.github.forsyde.io.meta.MetaPackage#getVertexTraitRealProperty_Default()
   * @model
   * @generated
   */
  String getDefault();

  /**
   * Sets the value of the '{@link io.github.forsyde.io.meta.VertexTraitRealProperty#getDefault <em>Default</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Default</em>' attribute.
   * @see #getDefault()
   * @generated
   */
  void setDefault(String value);

} // VertexTraitRealProperty
