/**
 * generated by Xtext 2.25.0
 */
package io.github.forsyde.io.meta;


/**
 * &lt;!-- begin-user-doc --&gt;
 * A representation of the model object '<em><b>Vertex Trait Array Property</b>&lt;/em&gt;'.
 * &lt;!-- end-user-doc --&gt;
 *
 * &lt; &gt;
 * The following features are supported:
 * &lt;/p&gt;
 * &lt; &gt;
 *   <li>{@link io.github.forsyde.io.meta.VertexTraitArrayProperty#getItemType <em>Item Type</em>}&lt;/li&gt;
 * &lt;/ul&gt;
 *
 * @see io.github.forsyde.io.meta.MetaPackage#getVertexTraitArrayProperty()
 * @model
 * @generated
 */
public interface VertexTraitArrayProperty extends VertexTraitPropertyType
{
  /**
   * Returns the value of the '<em><b>Item Type</b>&lt;/em&gt;' containment reference.
   * &lt;!-- begin-user-doc --&gt;
   * &lt;!-- end-user-doc --&gt;
   * @return the value of the '<em>Item Type&lt;/em&gt;' containment reference.
   * @see #setItemType(VertexTraitPropertyType)
   * @see io.github.forsyde.io.meta.MetaPackage#getVertexTraitArrayProperty_ItemType()
   * @model containment="true"
   * @generated
   */
  VertexTraitPropertyType getItemType();

  /**
   * Sets the value of the '{@link io.github.forsyde.io.meta.VertexTraitArrayProperty#getItemType <em>Item Type&lt;/em&gt;}' containment reference.
   * &lt;!-- begin-user-doc --&gt;
   * &lt;!-- end-user-doc --&gt;
   * @param value the new value of the '<em>Item Type&lt;/em&gt;' containment reference.
   * @see #getItemType()
   * @generated
   */
  void setItemType(VertexTraitPropertyType value);

} // VertexTraitArrayProperty
