/**
 * generated by Xtext 2.25.0
 */
package io.github.forsyde.io.meta;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Vertex Trait String Property</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link io.github.forsyde.io.meta.VertexTraitStringProperty#getDefault <em>Default</em>}</li>
 * </ul>
 *
 * @see io.github.forsyde.io.meta.MetaPackage#getVertexTraitStringProperty()
 * @model
 * @generated
 */
public interface VertexTraitStringProperty extends VertexTraitPropertyType
{
  /**
   * Returns the value of the '<em><b>Default</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Default</em>' attribute.
   * @see #setDefault(String)
   * @see io.github.forsyde.io.meta.MetaPackage#getVertexTraitStringProperty_Default()
   * @model
   * @generated
   */
  String getDefault();

  /**
   * Sets the value of the '{@link io.github.forsyde.io.meta.VertexTraitStringProperty#getDefault <em>Default</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Default</em>' attribute.
   * @see #getDefault()
   * @generated
   */
  void setDefault(String value);

} // VertexTraitStringProperty
