/**
 * generated by Xtext 2.25.0
 */
package io.github.forsyde.io.meta;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import org.eclipse.emf.common.util.Enumerator;

/**
 * &lt;!-- begin-user-doc --&gt;
 * A representation of the literals of the enumeration '<em><b>Vertex Trait Port Direction</b>&lt;/em&gt;',
 * and utility methods for working with them.
 * &lt;!-- end-user-doc --&gt;
 * @see io.github.forsyde.io.meta.MetaPackage#getVertexTraitPortDirection()
 * @model
 * @generated
 */
public enum VertexTraitPortDirection implements Enumerator
{
  /**
   * The '<em><b>BIDIRECTIONAL</b>&lt;/em&gt;' literal object.
   * &lt;!-- begin-user-doc --&gt;
   * &lt;!-- end-user-doc --&gt;
   * @see #BIDIRECTIONAL_VALUE
   * @generated
   * @ordered
   */
  BIDIRECTIONAL(0, "BIDIRECTIONAL", "inout"),

  /**
   * The '<em><b>OUTGOING</b>&lt;/em&gt;' literal object.
   * &lt;!-- begin-user-doc --&gt;
   * &lt;!-- end-user-doc --&gt;
   * @see #OUTGOING_VALUE
   * @generated
   * @ordered
   */
  OUTGOING(1, "OUTGOING", "out"),

  /**
   * The '<em><b>INCOMING</b>&lt;/em&gt;' literal object.
   * &lt;!-- begin-user-doc --&gt;
   * &lt;!-- end-user-doc --&gt;
   * @see #INCOMING_VALUE
   * @generated
   * @ordered
   */
  INCOMING(2, "INCOMING", "in");

  /**
   * The '<em><b>BIDIRECTIONAL</b>&lt;/em&gt;' literal value.
   * &lt;!-- begin-user-doc --&gt;
   * &lt;!-- end-user-doc --&gt;
   * @see #BIDIRECTIONAL
   * @model literal="inout"
   * @generated
   * @ordered
   */
  public static final int BIDIRECTIONAL_VALUE = 0;

  /**
   * The '<em><b>OUTGOING</b>&lt;/em&gt;' literal value.
   * &lt;!-- begin-user-doc --&gt;
   * &lt;!-- end-user-doc --&gt;
   * @see #OUTGOING
   * @model literal="out"
   * @generated
   * @ordered
   */
  public static final int OUTGOING_VALUE = 1;

  /**
   * The '<em><b>INCOMING</b>&lt;/em&gt;' literal value.
   * &lt;!-- begin-user-doc --&gt;
   * &lt;!-- end-user-doc --&gt;
   * @see #INCOMING
   * @model literal="in"
   * @generated
   * @ordered
   */
  public static final int INCOMING_VALUE = 2;

  /**
   * An array of all the '<em><b>Vertex Trait Port Direction</b>&lt;/em&gt;' enumerators.
   * &lt;!-- begin-user-doc --&gt;
   * &lt;!-- end-user-doc --&gt;
   * @generated
   */
  private static final VertexTraitPortDirection[] VALUES_ARRAY =
    new VertexTraitPortDirection[]
    {
      BIDIRECTIONAL,
      OUTGOING,
      INCOMING,
    };

  /**
   * A public read-only list of all the '<em><b>Vertex Trait Port Direction</b>&lt;/em&gt;' enumerators.
   * &lt;!-- begin-user-doc --&gt;
   * &lt;!-- end-user-doc --&gt;
   * @generated
   */
  public static final List<VertexTraitPortDirection> VALUES = Collections.unmodifiableList(Arrays.asList(VALUES_ARRAY));

  /**
   * Returns the '<em><b>Vertex Trait Port Direction</b>&lt;/em&gt;' literal with the specified literal value.
   * &lt;!-- begin-user-doc --&gt;
   * &lt;!-- end-user-doc --&gt;
   * @param literal the literal.
   * @return the matching enumerator or null&lt;/code&gt;.
   * @generated
   */
  public static VertexTraitPortDirection get(String literal)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      VertexTraitPortDirection result = VALUES_ARRAY[i];
      if (result.toString().equals(literal))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Vertex Trait Port Direction</b>&lt;/em&gt;' literal with the specified name.
   * &lt;!-- begin-user-doc --&gt;
   * &lt;!-- end-user-doc --&gt;
   * @param name the name.
   * @return the matching enumerator or null&lt;/code&gt;.
   * @generated
   */
  public static VertexTraitPortDirection getByName(String name)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      VertexTraitPortDirection result = VALUES_ARRAY[i];
      if (result.getName().equals(name))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Vertex Trait Port Direction</b>&lt;/em&gt;' literal with the specified integer value.
   * &lt;!-- begin-user-doc --&gt;
   * &lt;!-- end-user-doc --&gt;
   * @param value the integer value.
   * @return the matching enumerator or null&lt;/code&gt;.
   * @generated
   */
  public static VertexTraitPortDirection get(int value)
  {
    switch (value)
    {
      case BIDIRECTIONAL_VALUE: return BIDIRECTIONAL;
      case OUTGOING_VALUE: return OUTGOING;
      case INCOMING_VALUE: return INCOMING;
    }
    return null;
  }

  /**
   * &lt;!-- begin-user-doc --&gt;
   * &lt;!-- end-user-doc --&gt;
   * @generated
   */
  private final int value;

  /**
   * &lt;!-- begin-user-doc --&gt;
   * &lt;!-- end-user-doc --&gt;
   * @generated
   */
  private final String name;

  /**
   * &lt;!-- begin-user-doc --&gt;
   * &lt;!-- end-user-doc --&gt;
   * @generated
   */
  private final String literal;

  /**
   * Only this class can construct instances.
   * &lt;!-- begin-user-doc --&gt;
   * &lt;!-- end-user-doc --&gt;
   * @generated
   */
  private VertexTraitPortDirection(int value, String name, String literal)
  {
    this.value = value;
    this.name = name;
    this.literal = literal;
  }

  /**
   * &lt;!-- begin-user-doc --&gt;
   * &lt;!-- end-user-doc --&gt;
   * @generated
   */
  @Override
  public int getValue()
  {
    return value;
  }

  /**
   * &lt;!-- begin-user-doc --&gt;
   * &lt;!-- end-user-doc --&gt;
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * &lt;!-- begin-user-doc --&gt;
   * &lt;!-- end-user-doc --&gt;
   * @generated
   */
  @Override
  public String getLiteral()
  {
    return literal;
  }

  /**
   * Returns the literal value of the enumerator, which is its string representation.
   * &lt;!-- begin-user-doc --&gt;
   * &lt;!-- end-user-doc --&gt;
   * @generated
   */
  @Override
  public String toString()
  {
    return literal;
  }
  
} //VertexTraitPortDirection
