/**
 * generated by Xtext 2.25.0
 */
package io.github.forsyde.io.meta;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Vertex Trait</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link io.github.forsyde.io.meta.VertexTrait#getName <em>Name</em>}</li>
 *   <li>{@link io.github.forsyde.io.meta.VertexTrait#getRefines <em>Refines</em>}</li>
 *   <li>{@link io.github.forsyde.io.meta.VertexTrait#getPorts <em>Ports</em>}</li>
 *   <li>{@link io.github.forsyde.io.meta.VertexTrait#getProperties <em>Properties</em>}</li>
 * </ul>
 *
 * @see io.github.forsyde.io.meta.MetaPackage#getVertexTrait()
 * @model
 * @generated
 */
public interface VertexTrait extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see io.github.forsyde.io.meta.MetaPackage#getVertexTrait_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link io.github.forsyde.io.meta.VertexTrait#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Refines</b></em>' reference list.
   * The list contents are of type {@link io.github.forsyde.io.meta.VertexTrait}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Refines</em>' reference list.
   * @see io.github.forsyde.io.meta.MetaPackage#getVertexTrait_Refines()
   * @model
   * @generated
   */
  EList<VertexTrait> getRefines();

  /**
   * Returns the value of the '<em><b>Ports</b></em>' containment reference list.
   * The list contents are of type {@link io.github.forsyde.io.meta.VertexTraitPort}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ports</em>' containment reference list.
   * @see io.github.forsyde.io.meta.MetaPackage#getVertexTrait_Ports()
   * @model containment="true"
   * @generated
   */
  EList<VertexTraitPort> getPorts();

  /**
   * Returns the value of the '<em><b>Properties</b></em>' containment reference list.
   * The list contents are of type {@link io.github.forsyde.io.meta.VertexTraitProperty}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Properties</em>' containment reference list.
   * @see io.github.forsyde.io.meta.MetaPackage#getVertexTrait_Properties()
   * @model containment="true"
   * @generated
   */
  EList<VertexTraitProperty> getProperties();

} // VertexTrait
