/**
 * generated by Xtext 2.25.0
 */
package io.github.forsyde.io.meta;


/**
 * &lt;!-- begin-user-doc --&gt;
 * A representation of the model object '<em><b>Vertex Trait Bool Property</b>&lt;/em&gt;'.
 * &lt;!-- end-user-doc --&gt;
 *
 * &lt; &gt;
 * The following features are supported:
 * &lt;/p&gt;
 * &lt; &gt;
 *   <li>{@link io.github.forsyde.io.meta.VertexTraitBoolProperty#isDefault <em>Default</em>}&lt;/li&gt;
 * &lt;/ul&gt;
 *
 * @see io.github.forsyde.io.meta.MetaPackage#getVertexTraitBoolProperty()
 * @model
 * @generated
 */
public interface VertexTraitBoolProperty extends VertexTraitPropertyType
{
  /**
   * Returns the value of the '<em><b>Default</b>&lt;/em&gt;' attribute.
   * &lt;!-- begin-user-doc --&gt;
   * &lt;!-- end-user-doc --&gt;
   * @return the value of the '<em>Default&lt;/em&gt;' attribute.
   * @see #setDefault(boolean)
   * @see io.github.forsyde.io.meta.MetaPackage#getVertexTraitBoolProperty_Default()
   * @model
   * @generated
   */
  boolean isDefault();

  /**
   * Sets the value of the '{@link io.github.forsyde.io.meta.VertexTraitBoolProperty#isDefault <em>Default&lt;/em&gt;}' attribute.
   * &lt;!-- begin-user-doc --&gt;
   * &lt;!-- end-user-doc --&gt;
   * @param value the new value of the '<em>Default&lt;/em&gt;' attribute.
   * @see #isDefault()
   * @generated
   */
  void setDefault(boolean value);

} // VertexTraitBoolProperty
