/**
 * generated by Xtext 2.25.0
 */
package io.github.forsyde.io.meta;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Vertex Trait Bool Property</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link io.github.forsyde.io.meta.VertexTraitBoolProperty#isDefault <em>Default</em>}</li>
 * </ul>
 *
 * @see io.github.forsyde.io.meta.MetaPackage#getVertexTraitBoolProperty()
 * @model
 * @generated
 */
public interface VertexTraitBoolProperty extends VertexTraitPropertyType
{
  /**
   * Returns the value of the '<em><b>Default</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Default</em>' attribute.
   * @see #setDefault(boolean)
   * @see io.github.forsyde.io.meta.MetaPackage#getVertexTraitBoolProperty_Default()
   * @model
   * @generated
   */
  boolean isDefault();

  /**
   * Sets the value of the '{@link io.github.forsyde.io.meta.VertexTraitBoolProperty#isDefault <em>Default</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Default</em>' attribute.
   * @see #isDefault()
   * @generated
   */
  void setDefault(boolean value);

} // VertexTraitBoolProperty
