//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.09 at 03:43:10 PM CET 
//


package forsyde.io.java.adapters.xmi;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * &lt; &gt;Java class for ArrayVertexPropertyType complex type.
 * 
 * &lt; &gt;The following schema fragment specifies the expected content contained within this class.
 * 
 * &lt; &gt;
 * &lt;complexType name="ArrayVertexPropertyType"&gt;
 *   &lt;   &gt;
 *     &lt;extension base="{forsyde.io.trait.hierarchy}VertexPropertyType"&gt;
 *       &lt;       &gt;
 *         &lt;element name="valueTypes" type="{forsyde.io.trait.hierarchy}VertexPropertyType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * &lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ArrayVertexPropertyType", propOrder = {
    "valueTypes"
})
public class ArrayVertexPropertyType
    extends VertexPropertyType
{

    protected VertexPropertyType valueTypes;

    /**
     * Gets the value of the valueTypes property.
	 * @return valueTypes
     * 
     *     possible object is
     *     {@link VertexPropertyType }
     *     
     */
    public VertexPropertyType getValueTypes() {
        return valueTypes;
    }

    /**
     * Sets the value of the valueTypes property.
     * 
     * @param value
     *     allowed object is
     *     {@link VertexPropertyType }
     *     
     */
    public void setValueTypes(VertexPropertyType value) {
        this.valueTypes = value;
    }

}
