//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.09 at 03:43:10 PM CET 
//


package forsyde.io.java.adapters.xmi;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * &lt; &gt;Java class for PortDirectionEnum.
 * 
 * &lt; &gt;The following schema fragment specifies the expected content contained within this class.
 * &lt; &gt;
 * &lt; &gt;
 * &lt;simpleType name="PortDirectionEnum"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NCName"&gt;
 *     &lt;enumeration value="FORWARD"/&gt;
 *     &lt;enumeration value="BACKWARD"/&gt;
 *     &lt;enumeration value="BIDIRECTIONAL"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * &lt;/pre&gt;
 * 
 */
@XmlType(name = "PortDirectionEnum")
@XmlEnum
public enum PortDirectionEnum {

    FORWARD,
    BACKWARD,
    BIDIRECTIONAL;

    public String value() {
        return name();
    }

    public static PortDirectionEnum fromValue(String v) {
        return valueOf(v);
    }

}
