//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.09 at 03:43:10 PM CET 
//


package forsyde.io.java.adapters.xmi;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * &lt; &gt;Java class for PortSpec complex type.
 * 
 * &lt; &gt;The following schema fragment specifies the expected content contained within this class.
 * 
 * &lt; &gt;
 * &lt;complexType name="PortSpec"&gt;
 *   &lt;   &gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="direction" type="{forsyde.io.trait.hierarchy}PortDirectionEnum" /&gt;
 *       &lt;attribute name="connectedVertexTrait" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="connectedEdgeTrait" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * &lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PortSpec")
public class PortSpec {

    @XmlAttribute(name = "name")
    protected String name;
    @XmlAttribute(name = "direction")
    protected PortDirectionEnum direction;
    @XmlAttribute(name = "connectedVertexTrait")
    protected String connectedVertexTrait;
    @XmlAttribute(name = "connectedEdgeTrait")
    protected String connectedEdgeTrait;

    /**
     * Gets the value of the name property.
	 * @return name
     * 
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the direction property.
	 * @return direction
     * 
     *     possible object is
     *     {@link PortDirectionEnum }
     *     
     */
    public PortDirectionEnum getDirection() {
        return direction;
    }

    /**
     * Sets the value of the direction property.
     * 
     * @param value
     *     allowed object is
     *     {@link PortDirectionEnum }
     *     
     */
    public void setDirection(PortDirectionEnum value) {
        this.direction = value;
    }

    /**
     * Gets the value of the connectedVertexTrait property.
	 * @return connectedVertexTrait
     * 
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConnectedVertexTrait() {
        return connectedVertexTrait;
    }

    /**
     * Sets the value of the connectedVertexTrait property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConnectedVertexTrait(String value) {
        this.connectedVertexTrait = value;
    }

    /**
     * Gets the value of the connectedEdgeTrait property.
	 * @return connectedEdgeTrait
     * 
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConnectedEdgeTrait() {
        return connectedEdgeTrait;
    }

    /**
     * Sets the value of the connectedEdgeTrait property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConnectedEdgeTrait(String value) {
        this.connectedEdgeTrait = value;
    }

}
