//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.09 at 03:43:10 PM CET 
//


package forsyde.io.java.adapters.xmi;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * &lt; &gt;Java class for VertexTraitSpec complex type.
 * 
 * &lt; &gt;The following schema fragment specifies the expected content contained within this class.
 * 
 * &lt; &gt;
 * &lt;complexType name="VertexTraitSpec"&gt;
 *   &lt;   &gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;       &gt;
 *         &lt;element name="requiredPorts" type="{forsyde.io.trait.hierarchy}PortSpec" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="requiredProperties" type="{forsyde.io.trait.hierarchy}VertexPropertySpec" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="refinedTraits" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * &lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VertexTraitSpec", propOrder = {
    "requiredPorts",
    "requiredProperties"
})
public class VertexTraitSpec {

    protected List<PortSpec> requiredPorts;
    protected List<VertexPropertySpec> requiredProperties;
    @XmlAttribute(name = "name")
    protected String name;
    @XmlAttribute(name = "refinedTraits")
    protected String refinedTraits;

    /**
     * Gets the value of the requiredPorts property.
     * 
     * &lt; &gt;
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a set&lt;/CODE&gt; method for the requiredPorts property.
     * 
     * &lt; &gt;
     * For example, to add a new item, do as follows:
     * &lt; &gt;
     *    getRequiredPorts().add(newItem);
     * &lt;/pre&gt;
     * 
     * 
     * &lt; &gt;
     * Objects of the following type(s) are allowed in the list
     * {@link PortSpec }
* @return PortSpec
     * 
     * 
     */
    public List<PortSpec> getRequiredPorts() {
        if (requiredPorts == null) {
            requiredPorts = new ArrayList<PortSpec>();
        }
        return this.requiredPorts;
    }

    /**
     * Gets the value of the requiredProperties property.
     * 
     * &lt; &gt;
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a set&lt;/CODE&gt; method for the requiredProperties property.
     * 
     * &lt; &gt;
     * For example, to add a new item, do as follows:
     * &lt; &gt;
     *    getRequiredProperties().add(newItem);
     * &lt;/pre&gt;
     * 
     * 
     * &lt; &gt;
     * Objects of the following type(s) are allowed in the list
     * {@link VertexPropertySpec }
* @return VertexPropertySpec
     * 
     * 
     */
    public List<VertexPropertySpec> getRequiredProperties() {
        if (requiredProperties == null) {
            requiredProperties = new ArrayList<VertexPropertySpec>();
        }
        return this.requiredProperties;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the refinedTraits property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRefinedTraits() {
        return refinedTraits;
    }

    /**
     * Sets the value of the refinedTraits property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRefinedTraits(String value) {
        this.refinedTraits = value;
    }

}
