/**
 *
 * $Id$
 */
package forsyde.io.trait.hierarchy.validation;

import forsyde.io.trait.hierarchy.VertexPropertyDefault;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link forsyde.io.trait.hierarchy.IntMapVertexPropertyDefault}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface IntMapVertexPropertyDefaultValidator {
	boolean validate();

	boolean validateValues(EList<VertexPropertyDefault> value);
	boolean validateIndexes(EList<Integer> value);
}
