/**
 *
 * $Id$
 */
package forsyde.io.trait.hierarchy.validation;

import forsyde.io.trait.hierarchy.PortSpec;
import forsyde.io.trait.hierarchy.VertexPropertySpec;
import forsyde.io.trait.hierarchy.VertexTraitSpec;
import org.eclipse.emf.common.util.EList;


/**
 * A sample validator interface for {@link forsyde.io.trait.hierarchy.VertexTraitSpec}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface VertexTraitSpecValidator {
	boolean validate();

	boolean validateName(String value);

	boolean validateRefinedTraits(EList<VertexTraitSpec> value);

	boolean validateRequiredPorts(EList<PortSpec> value);

	boolean validateRequiredProperties(EList<VertexPropertySpec> value);

	boolean validateRefinesTraits(EList<VertexTraitSpec> value);
}
