/**
 * generated by Xtext 2.25.0
 */
package io.github.forsyde.io.meta.impl;

import io.github.forsyde.io.meta.MetaPackage;
import io.github.forsyde.io.meta.VertexTraitObjectProperty;
import io.github.forsyde.io.meta.VertexTraitPropertyType;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Vertex Trait Object Property</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link io.github.forsyde.io.meta.impl.VertexTraitObjectPropertyImpl#getKeyType <em>Key Type</em>}</li>
 *   <li>{@link io.github.forsyde.io.meta.impl.VertexTraitObjectPropertyImpl#getValueType <em>Value Type</em>}</li>
 * </ul>
 *
 * @generated
 */
public class VertexTraitObjectPropertyImpl extends VertexTraitPropertyTypeImpl implements VertexTraitObjectProperty
{
  /**
   * The cached value of the '{@link #getKeyType() <em>Key Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getKeyType()
   * @generated
   * @ordered
   */
  protected VertexTraitPropertyType keyType;

  /**
   * The cached value of the '{@link #getValueType() <em>Value Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getValueType()
   * @generated
   * @ordered
   */
  protected VertexTraitPropertyType valueType;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected VertexTraitObjectPropertyImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MetaPackage.Literals.VERTEX_TRAIT_OBJECT_PROPERTY;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public VertexTraitPropertyType getKeyType()
  {
    return keyType;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetKeyType(VertexTraitPropertyType newKeyType, NotificationChain msgs)
  {
    VertexTraitPropertyType oldKeyType = keyType;
    keyType = newKeyType;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MetaPackage.VERTEX_TRAIT_OBJECT_PROPERTY__KEY_TYPE, oldKeyType, newKeyType);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setKeyType(VertexTraitPropertyType newKeyType)
  {
    if (newKeyType != keyType)
    {
      NotificationChain msgs = null;
      if (keyType != null)
        msgs = ((InternalEObject)keyType).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MetaPackage.VERTEX_TRAIT_OBJECT_PROPERTY__KEY_TYPE, null, msgs);
      if (newKeyType != null)
        msgs = ((InternalEObject)newKeyType).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MetaPackage.VERTEX_TRAIT_OBJECT_PROPERTY__KEY_TYPE, null, msgs);
      msgs = basicSetKeyType(newKeyType, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MetaPackage.VERTEX_TRAIT_OBJECT_PROPERTY__KEY_TYPE, newKeyType, newKeyType));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public VertexTraitPropertyType getValueType()
  {
    return valueType;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetValueType(VertexTraitPropertyType newValueType, NotificationChain msgs)
  {
    VertexTraitPropertyType oldValueType = valueType;
    valueType = newValueType;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MetaPackage.VERTEX_TRAIT_OBJECT_PROPERTY__VALUE_TYPE, oldValueType, newValueType);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setValueType(VertexTraitPropertyType newValueType)
  {
    if (newValueType != valueType)
    {
      NotificationChain msgs = null;
      if (valueType != null)
        msgs = ((InternalEObject)valueType).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MetaPackage.VERTEX_TRAIT_OBJECT_PROPERTY__VALUE_TYPE, null, msgs);
      if (newValueType != null)
        msgs = ((InternalEObject)newValueType).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MetaPackage.VERTEX_TRAIT_OBJECT_PROPERTY__VALUE_TYPE, null, msgs);
      msgs = basicSetValueType(newValueType, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MetaPackage.VERTEX_TRAIT_OBJECT_PROPERTY__VALUE_TYPE, newValueType, newValueType));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MetaPackage.VERTEX_TRAIT_OBJECT_PROPERTY__KEY_TYPE:
        return basicSetKeyType(null, msgs);
      case MetaPackage.VERTEX_TRAIT_OBJECT_PROPERTY__VALUE_TYPE:
        return basicSetValueType(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MetaPackage.VERTEX_TRAIT_OBJECT_PROPERTY__KEY_TYPE:
        return getKeyType();
      case MetaPackage.VERTEX_TRAIT_OBJECT_PROPERTY__VALUE_TYPE:
        return getValueType();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MetaPackage.VERTEX_TRAIT_OBJECT_PROPERTY__KEY_TYPE:
        setKeyType((VertexTraitPropertyType)newValue);
        return;
      case MetaPackage.VERTEX_TRAIT_OBJECT_PROPERTY__VALUE_TYPE:
        setValueType((VertexTraitPropertyType)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MetaPackage.VERTEX_TRAIT_OBJECT_PROPERTY__KEY_TYPE:
        setKeyType((VertexTraitPropertyType)null);
        return;
      case MetaPackage.VERTEX_TRAIT_OBJECT_PROPERTY__VALUE_TYPE:
        setValueType((VertexTraitPropertyType)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MetaPackage.VERTEX_TRAIT_OBJECT_PROPERTY__KEY_TYPE:
        return keyType != null;
      case MetaPackage.VERTEX_TRAIT_OBJECT_PROPERTY__VALUE_TYPE:
        return valueType != null;
    }
    return super.eIsSet(featureID);
  }

} //VertexTraitObjectPropertyImpl
