/**
 * generated by Xtext 2.25.0
 */
package io.github.forsyde.io.meta.impl;

import io.github.forsyde.io.meta.MetaPackage;
import io.github.forsyde.io.meta.VertexTraitPropertyType;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * &lt;!-- begin-user-doc --&gt;
 * An implementation of the model object '<em><b>Vertex Trait Property Type</b>&lt;/em&gt;'.
 * &lt;!-- end-user-doc --&gt;
 *
 * @generated
 */
public class VertexTraitPropertyTypeImpl extends MinimalEObjectImpl.Container implements VertexTraitPropertyType
{
  /**
   * &lt;!-- begin-user-doc --&gt;
   * &lt;!-- end-user-doc --&gt;
   * @generated
   */
  protected VertexTraitPropertyTypeImpl()
  {
    super();
  }

  /**
   * &lt;!-- begin-user-doc --&gt;
   * &lt;!-- end-user-doc --&gt;
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MetaPackage.Literals.VERTEX_TRAIT_PROPERTY_TYPE;
  }

} //VertexTraitPropertyTypeImpl
