/**
 * generated by Xtext 2.25.0
 */
package io.github.forsyde.io.meta.impl;

import io.github.forsyde.io.meta.MetaPackage;
import io.github.forsyde.io.meta.VertexTraitArrayProperty;
import io.github.forsyde.io.meta.VertexTraitPropertyType;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Vertex Trait Array Property</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link io.github.forsyde.io.meta.impl.VertexTraitArrayPropertyImpl#getItemType <em>Item Type</em>}</li>
 * </ul>
 *
 * @generated
 */
public class VertexTraitArrayPropertyImpl extends VertexTraitPropertyTypeImpl implements VertexTraitArrayProperty
{
  /**
   * The cached value of the '{@link #getItemType() <em>Item Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getItemType()
   * @generated
   * @ordered
   */
  protected VertexTraitPropertyType itemType;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected VertexTraitArrayPropertyImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MetaPackage.Literals.VERTEX_TRAIT_ARRAY_PROPERTY;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public VertexTraitPropertyType getItemType()
  {
    return itemType;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetItemType(VertexTraitPropertyType newItemType, NotificationChain msgs)
  {
    VertexTraitPropertyType oldItemType = itemType;
    itemType = newItemType;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MetaPackage.VERTEX_TRAIT_ARRAY_PROPERTY__ITEM_TYPE, oldItemType, newItemType);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setItemType(VertexTraitPropertyType newItemType)
  {
    if (newItemType != itemType)
    {
      NotificationChain msgs = null;
      if (itemType != null)
        msgs = ((InternalEObject)itemType).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MetaPackage.VERTEX_TRAIT_ARRAY_PROPERTY__ITEM_TYPE, null, msgs);
      if (newItemType != null)
        msgs = ((InternalEObject)newItemType).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MetaPackage.VERTEX_TRAIT_ARRAY_PROPERTY__ITEM_TYPE, null, msgs);
      msgs = basicSetItemType(newItemType, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MetaPackage.VERTEX_TRAIT_ARRAY_PROPERTY__ITEM_TYPE, newItemType, newItemType));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MetaPackage.VERTEX_TRAIT_ARRAY_PROPERTY__ITEM_TYPE:
        return basicSetItemType(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MetaPackage.VERTEX_TRAIT_ARRAY_PROPERTY__ITEM_TYPE:
        return getItemType();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MetaPackage.VERTEX_TRAIT_ARRAY_PROPERTY__ITEM_TYPE:
        setItemType((VertexTraitPropertyType)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MetaPackage.VERTEX_TRAIT_ARRAY_PROPERTY__ITEM_TYPE:
        setItemType((VertexTraitPropertyType)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MetaPackage.VERTEX_TRAIT_ARRAY_PROPERTY__ITEM_TYPE:
        return itemType != null;
    }
    return super.eIsSet(featureID);
  }

} //VertexTraitArrayPropertyImpl
