/**
 *
 * $Id$
 */
package forsyde.io.trait.hierarchy.validation;

import forsyde.io.trait.hierarchy.EdgeTraitSpec;
import forsyde.io.trait.hierarchy.PortDirectionEnum;
import forsyde.io.trait.hierarchy.VertexTraitSpec;

/**
 * A sample validator interface for {@link forsyde.io.trait.hierarchy.PortSpec}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface PortSpecValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateMultiple(boolean value);
	boolean validateOrdered(boolean value);
	boolean validateDirection(PortDirectionEnum value);
	boolean validateConnectedVertexTrait(VertexTraitSpec value);
	boolean validateConnectedEdgeTrait(EdgeTraitSpec value);
}
