/*
 * generated by Xtext 2.25.0
 */
package io.github.forsyde.io.parser.antlr;

import com.google.inject.Inject;
import io.github.forsyde.io.parser.antlr.internal.InternalMetaParser;
import io.github.forsyde.io.services.MetaGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class MetaParser extends AbstractAntlrParser {

	@Inject
	private MetaGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalMetaParser createParser(XtextTokenStream stream) {
		return new InternalMetaParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public MetaGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MetaGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
